### ISSUE TITLE
Won't use this dict

### ISSUE THREAD

**Issue by gitfoxi** [cmusphinx/pocketsphinx#10]
Doing the adaptation tutorial: http://cmusphinx.sourceforge.net/wiki/tutorialadapt?s[]=adaptation

Suggests I use their dictionary: http://www.speech.cs.cmu.edu/cmusphinx/moindocs/arctic20.dic

Something like:

```
pocketsphinx_batch \
 -adcin yes \ 
 -cepdir . \
 -cepext .wav \
 -dict arctic20.dic \
 -ctl arctic20.fileids \
 -hmm model-adapt \
 -hyp adapation-test.hyp
```

In this case recognition drops to 0% (was about 65% with the default dictionary).

**Comment by nshmyrev** [comment]
I updated the tutorial, it is using default dictionary now. The issue in your command line is that you need to specify language model and default language model is incompatible with arctic20.dic. Now it should be fine.

**Comment by gitfoxi** [comment]
Thanks! I'll try again.
