### ISSUE TITLE
Updated Microphone issue

### ISSUE THREAD

**Issue by darwinasm86** [cmusphinx/pocketsphinx#100]
This is still an issue.

Error opening audio device plughw:0,0 for capture: Connection refused
FATAL: "continuous.c", line 245: Failed to open audio device

Ive used:

pocketsphinx_continuous -inmic yes -adcdev plughw:0,0
pocketsphinx_continuous -inmic yes -adcdev default
pocketsphinx_continuous -inmic yes

cat /proc/asound/cards
0 [ALSA ]: bcm2835 - bcm2835 ALSA
bcm2835 ALSA
1 [Device ]: USB-Audio - USB PnP Sound Device
C-Media Electronics Inc. USB PnP Sound Device at usb-3f980000.usb-1.2, full spe

Im able to play and record using "aplay" and "arecord"

Edited 

sudo nano /etc/modprobe.d/alsa-base.conf
sudo nano /usr/share/alsa/alsa.conf

Im at a complete loss why I can't change the priority of the MIC or get it to work.
 
Best Regards,

Jason

**Comment by UNspawn-N4** [comment]
may be more easy to use pulseaudio. Install devel package libpulse-dev and reconfigure + rebuild sphinx and pocketsphinx.
my start script:
#!/bin/bash
pocketsphinx_continuous \
    -hmm sphinx/voxforge-de-r20141117/model_parameters/voxforge.cd_cont_3000 \
    -dict sphinx/voxgen/robo.dic \
    -inmic yes -vad_threshold 3.0\
    -lm sphinx/uwevoxgen/robotino.model.bin -logfn /dev/null -agc none

hope this helps

**Comment by darwinasm86** [comment]
Thank you Im looking at it now, i'll let you know how I fair...

**Comment by darwinasm86** [comment]
Ok I got it, I was under the impression that pulseaudio was automagically installed with raspien, but it wasnt, an install fixed my issue... now for the final step. running a python script when the wake word is detected.
