### ISSUE TITLE
Running Python Script when wake world detected

### ISSUE THREAD

**Issue by darwinasm86** [cmusphinx/pocketsphinx#102]
I cannot find any specific literature on running a python script when a specific wake word/ keyword is detected.

I have built a project that now is running a dictionary file I created with a specific keyword.

When pocketsphinx_continuos is executed I can see the keyword displayed when I say it out loud.

I also have a python script that runs controlling a GPIO on the raspberry pi, and this runs one time. It checks the status of one GPIO, and if the state is 0, then toggles another GPIO and ends.

How do I run the script when the keyword is detected by Sphinx?

**Comment by nshmyrev** [comment]
Such questions better asked on stackoverflow.
