### ISSUE TITLE
Issue in compilation package on fedora27

### ISSUE THREAD

**Issue by kamalmeh** [cmusphinx/pocketsphinx#103]
I am getting below error while compiling the package.

make[2]: Entering directory '/home/kh08603/pocketsphinx-5prealpha/src/programs'
/bin/sh ../../libtool  --tag=CC   --mode=link gcc -I../../include -I../../src/libpocketsphinx -I../../include -g -O2 -Wall  -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/lib -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/src/libsphinxad -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/src/libsphinxbase -o pocketsphinx_batch batch.o ../../src/libpocketsphinx/libpocketsphinx.la -lsphinxbase
libtool: link: gcc -I../../include -I../../src/libpocketsphinx -I../../include -g -O2 -Wall -o .libs/pocketsphinx_batch batch.o  -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/lib -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/src/libsphinxad -L/home/kh08603/pocketsphinx-5prealpha/../sphinxbase/src/libsphinxbase ../../src/libpocketsphinx/.libs/libpocketsphinx.so /home/kh08603/pocketsphinx-5prealpha/../sphinxbase/src/libsphinxbase/.libs/libsphinxbase.so /usr/lib64/libasound.so -ldl -lrt -lpthread -lm -Wl,-rpath -Wl,/usr/local/lib
../../src/libpocketsphinx/.libs/libpocketsphinx.so: undefined reference to `err_set_debug_level'
../../src/libpocketsphinx/.libs/libpocketsphinx.so: undefined reference to `E_DEBUGCONT'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:440: pocketsphinx_batch] Error 1
make[2]: Leaving directory '/home/kh08603/pocketsphinx-5prealpha/src/programs'
make[1]: *** [Makefile:381: all-recursive] Error 1
make[1]: Leaving directory '/home/kh08603/pocketsphinx-5prealpha/src'
make: *** [Makefile:476: all-recursive] Error 1

Can anyone advise why it is coming and how can I resolve it?

**Comment by nshmyrev** [comment]
Clone both packages from github.

**Comment by kamalmeh** [comment]
I downloaded the sphinxbase package for Ubuntu and then build it to
install. It worked fine. The package downloaded from git repository was in
consistent. Err.h header file is not up to date.

Thanks
Kamal
