### ISSUE TITLE
Build-breaking change to acmod.c

### ISSUE THREAD

**Issue by alexanderkoller** [cmusphinx/pocketsphinx#104]
Hi,

as @sjfricke mentioned in a comment, a change to acmod.c in the commit https://github.com/cmusphinx/pocketsphinx/commit/9221bf3ecf3da14dd5ce30d3962983c436ed7e64 breaks the build.

This means that "make" aborts with an error message, and pocketsphinx cannot be built successfully. I can confirm that I get the exact same error message that he did.

Any chance this could be fixed soon, so new versions of pocketsphinx will compile again? Thanks for your efforts!

Best,
Alexander.

**Comment by nshmyrev** [comment]
Update sphinxbase properly first.

**Comment by alexanderkoller** [comment]
What do you mean with "update"? I'm using the most recent version of sphinxbase (5prealpha) from Sourceforge, as indicated in the pocketsphinx README.

**Comment by nshmyrev** [comment]
You should have one from github, not from sourceforge.

**Comment by alexanderkoller** [comment]
Ok, that works. You might want to clarify the README.md, so other people don't run into the same problem.
