### ISSUE TITLE
Python functions need to type check their arguments

### ISSUE THREAD

**Issue by gitfoxi** [cmusphinx/pocketsphinx#11]
I added these 2 tiny little lines to a python script:

```
config.set_string('-agc', 'max')
config.set_string('-fillprob', '50')
```

Script was mostly working before but now it fails with:

```
Python(90397,0x7fff7d3af300) malloc: *** error for object 0x3e45798ee2308c3a: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Here is the full code listing:

```
#!/usr/local/bin/python

from pocketsphinx import *
import pyaudio

from os import environ, path
from itertools import izip
import sys

MODELDIR = "/usr/local//share/pocketsphinx/model/"

def print10best(decoder):
    # Access N best decodings.
    print 'Best 10 hypothesis: '
    for best, i in izip(decoder.nbest(), range(10)):
    	print best.hyp().best_score, best.hyp().hypstr

# Create a decoder with certain model
config = Decoder.default_config()
config.set_string('-hmm', path.join(MODELDIR, 'en-us/en-us'))
config.set_string('-lm', path.join(MODELDIR, 'en-us/en-us.lm.dmp'))
config.set_string('-dict', path.join(MODELDIR, 'en-us/cmudict-en-us.dict'))
config.set_string('-jsgf', './my.jsgf')
config.set_string('-dictcase', 'yes')
config.set_string('-agc', 'max')
config.set_string('-fillprob', '50')

decoder = Decoder(config)



p = pyaudio.PyAudio()

stream = p.open(format=pyaudio.paInt16, channels=1, rate=16000, input=True, frames_per_buffer=2048)
stream.start_stream()
in_speech_bf = True
decoder.start_utt()
while True:
    buf = stream.read(2048)
    if buf:
        decoder.process_raw(buf, False, False)
        try:
            if  decoder.hyp().hypstr != '':
                print 'Partial decoding result:', decoder.hyp().hypstr
                # print10best(decoder)
        except AttributeError:
            pass
        if decoder.get_in_speech():
            sys.stdout.write('.')
            sys.stdout.flush()
        if decoder.get_in_speech() != in_speech_bf:
            in_speech_bf = decoder.get_in_speech()
            if not in_speech_bf:
                decoder.end_utt()
                try:
                    if  decoder.hyp().hypstr != '':
                        print 'Stream decoding result:', decoder.hyp().hypstr
                except AttributeError:
                    pass
                decoder.start_utt()
    else:
        break
decoder.end_utt()
print 'An Error occured:', decoder.hyp().hypstr
```

**Comment by mbait** [comment]
You do not use `set_string` for integer arguments, but `set_int`.

**Comment by gitfoxi** [comment]
Update:

By process of elimination the culprit is: `config.set_string('-fillprob', '50')`

However it works on when i run like this:

`pocketsphinx_continuous -inmic yes -jsgf my.jsgf -dictcase yes -agc max -fillprob 50`

**Comment by mbait** [comment]
See my answer above.

**Comment by gitfoxi** [comment]
I think this argument is actually a floating-point value. There must be a special setter for that.

**Comment by mbait** [comment]
Guess the method name? ;-)

**Comment by gitfoxi** [comment]
`set_float` works fine.

Should we keep this bug open because functions should type check their arguments?

**Comment by nshmyrev** [comment]
Thank you, this issue is actually tracked on sourceforge

https://sourceforge.net/p/cmusphinx/bugs/386

**Comment by mbait** [comment]
Better to ask @nshmyrev, but my option is - no, because ultimately this code is generated.

**Comment by gitfoxi** [comment]
Even better. Swig can be programmed to generate the type checking.

http://www.swig.org/Doc1.3/Typemaps.html

**Comment by nshmyrev** [comment]
The thing here is that type of the configuration field is inside sphinxbase, so it must be retrieved from it.

**Comment by gitfoxi** [comment]
What is the program pocketsphinx_continuous doing? It must have some way to
call the underlying libraries with strings coherest correctly.

On Thu, Mar 19, 2015 at 1:39 PM, Nickolay V. Shmyrev <
notifications@github.com> wrote:

> The thing here is that type of the configuration field is inside
> sphinxbase, so it must be retrieved from it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cmusphinx/pocketsphinx/issues/11#issuecomment-83754672>
> .
>



-- 

-
Michael
