### ISSUE TITLE
pocketsphinx Decoder fails to initialise 

### ISSUE THREAD

**Issue by nickums** [cmusphinx/pocketsphinx#110]
Installed on windows10 and using the kws_test.py  test program

    decoder = Decoder(config)
  File "C:\Python\Python35\lib\site-packages\pocketsphinx\pocketsphinx.py", line 277, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1

**Comment by nshmyrev** [comment]
This is expected when model path is wrong or model files are missing.
