### ISSUE TITLE
continuous.c invalid argument

### ISSUE THREAD

**Issue by highvoltage379** [cmusphinx/pocketsphinx#112]
Hi,

I'm not sure if it's related to issues with pulse audio, but I have a strange error with "continuous.c". I want to do live speech recognition with a ReSpeaker far-field Mic Aray, so I'm using this command:

sudo pocketsphinx_continuous -adcdev plughw:1,0-dict fr.dic -hmm ./cmusphinx-fr-5.2 -lm ./fr-phone.lm.dmp -inmic yes

But I get this error:
Error opening audio device plughw:1,0 for capture: Invalid argument
FATAL: "continuous.c", line 245: Failed to open audio device

I know the device name is right, because I can record wav with this command:
arecord -v -D plughw:1,0 -f S16_LE -r 16000 -c 1 audio-test.wav

I don't have any problem when I'm using built-in microphone.

Am I missing something ?
Thank you in advance !

**Comment by nshmyrev** [comment]
Device names depend on the audio library that pocketsphinx uses

https://cmusphinx.github.io/wiki/faq/#q-failed-to-open-audio-devicedevdsp-no-such-file-or-directory

**Comment by highvoltage379** [comment]
Okay, but how could I know which library pocketsphinx is using ?

For others users, this command list the device names : 
pacmd list-sources | grep -e device.string -e 'name:'

(from https://wiki.archlinux.org/index.php/PulseAudio/Examples#Set_default_input_sources)

**Comment by highvoltage379** [comment]
If I understood correctly, this command is supposed to give the devices name, depending on pulse audio:
pacmd list-sources | grep -e device.string -e 'name:'

I got:
name: <alsa_output.pci-0000_01_00.1.hdmi-stereo.monitor>
		device.string = "2"
	name: <alsa_output.usb-SeeedStudio_ReSpeaker_MicArray_UAC2.0-00.analog-stereo.monitor>
		device.string = "1"
	name: <alsa_input.usb-SeeedStudio_ReSpeaker_MicArray_UAC2.0-00.analog-stereo>
		device.string = "front:1"
	name: <alsa_output.pci-0000_00_1b.0.analog-stereo.monitor>
		device.string = "0"
	name: <alsa_input.pci-0000_00_1b.0.analog-stereo>
		device.string = "front:0"

If I do cat /proc/asound/cards, I get : 
0 [PCH            ]: HDA-Intel - HDA Intel PCH
                      HDA Intel PCH at 0xc3110000 irq 30
 1 [UAC20          ]: USB-Audio - ReSpeaker MicArray UAC2.0
                      SeeedStudio ReSpeaker MicArray UAC2.0 at usb-0000:00:14.0-1, full speed
 2 [HDMI           ]: HDA-Intel - HDA ATI HDMI
                      HDA ATI HDMI at 0xc2020000 irq 31

So my guess is the device name I have to use is either "front:1" either "plughw1,0". But none of them are working. I really don't understand why.

**Comment by highvoltage379** [comment]
I double checked, and I'm definitely using PulseAudio for cross-compilation. So, the device name should be plughw:1,0 or hw:1,0.

By the way, the python script found here (https://github.com/respeaker/respeaker_python_library), it says: INFO:mic:Use ReSpeaker MicArray UAC2.0: USB Audio (hw:2,0)
And the speech recognition is working.

More and more confusing...

**Comment by nshmyrev** [comment]
> Okay, but how could I know which library pocketsphinx is using ?

       ldd /usr/local/bin/pocketsphinx_continuous

Alsa device names like `hw:1,0` might not be supported in pulseaudio. In pulseaudio you can set any device as a source and just use defaults for adcdev.
