### ISSUE TITLE
building shared object (libpocketsphinx.so) MacOS

### ISSUE THREAD

**Issue by megrimm** [cmusphinx/pocketsphinx#114]
Hello,

After build and install of lib my program states:

```
shared object load ERROR:
	dlopen(/usr/local/lib/libpocketsphinx.so, 9): image not found
```

I realize I only have libpocketsphinx.a, libpocketsphinx.dylib and libpocketsphinx.la
How do I build a .so ?

Seems according to `$ ./configure --help` shared libs are default no? `./configure --enable-shared` doesn't cut it so maybe im missing something?

Thanks!

**Comment by nshmyrev** [comment]
Change your code to open dylib instead of so.
