### ISSUE TITLE
Pocketsphinx C#

### ISSUE THREAD

**Issue by Sirozha1337** [cmusphinx/pocketsphinx#115]
Hi,

Where can I download wrapped library files for C#? 

(I can't build it myself, Visual Studio shows a hell of a lot of errors)

**Comment by nshmyrev** [comment]
> Where can I download wrapped library files for C#?

We do not provide this yet.

> (I can't build it myself, Visual Studio shows a hell of a lot of errors)

If you want help on this, you need to provide more details.
