### ISSUE TITLE
Runtime setting of parameters

### ISSUE THREAD

**Issue by mischmerz** [cmusphinx/pocketsphinx#117]
Hey - I am using pocketsphinx-5prealpha. I like to adjust -vad_threshold and maybe other parameters dynamically without restarting the engine, but ps_reinit bails out. I am currently terminating (ad_close, ps_free,cmd_ln_free) the recognition process and re-load the init 

cmd_ln_parse_r(NULL, cont_args_def, argc, argv, TRUE);
ps_default_search_args(config);
ps = ps_init(config);

which works ok, but costs me about 2 seconds (on a RaspberryPI) and I sometimes run into trouble with re-initializing the microphone sub-system.

Now - I wonder if this is a bug (read something about that somewhere else) or if I am doing somethinhg wrong. My client is written in C(++) .. 

Thanks
Michaela

**Comment by nshmyrev** [comment]
Changing vad_threshold in runtime is likely not a great idea. For other parameters you need to elaborate.

Usually you should not change parameters in runtime, that is why the API design does not include such an option

**Comment by mischmerz** [comment]
Thanks @nshmyrev  .  HerÄ's what I've been doing Nickolay: I am using pocketsphinx in combination with a small neural network that takes the STT output (the hyps pocketsphix returns) and tries to make sense of it in an home automation environment. This method acknowledges the fact that pocketshinx produces errors (such as "night" vs. "light") and resolves it successfully most of the time. The *only* thing bugging me is noise containg words such as a running TV set. Music and other noise is not a problem. I am measuring the time between starting and ending "in_speech" so I know when there is interference as my commands don't last longer than 1500msecs. What I would like to do is to up the vad threshold to the point that the measured time returns to "normal" and reduce the threshold once it is more quiet enough.  This would, of course, require me to yell my wake word, but it also dramatically reduces false wake word positives. In essences - I'd like to define a vad_threshold based on utterances  per second :)

**Comment by nshmyrev** [comment]
You probably need to develop some more intelligent VAD or use microphone array.

**Comment by mischmerz** [comment]
I see. Thanks.
