### ISSUE TITLE
Unable to influence sound level

### ISSUE THREAD

**Issue by mischmerz** [cmusphinx/pocketsphinx#118]
I just realized that - short of muting the audio - I am unable to influence the sound level within pocket sphinx. I wrapped the microphone in two big pool towels, arecord doesn't register any level anymore and even a recording to file is close to muted, still pocket sphinx is happily trying to read the few air pressure changes that may make it through the towels. agc is set to none and agcthresh is set to 0. 

I had to push a softvol plug into the microphone stream and to apply -50db to finally defeat sphinx. Now - that doesn't make a lot of sense as those severely throttled audio packets don't carry a lot of information anymore - even if sphinx would re-amplify them again. 

There *should* be a way to override the amplifying capacity of sphinx in order to be able to adjust to different environments (e.g. where there are speakers in the background that shouldn't influence the STT). I would have though that disabling agc would do just that. 

I am overlooking something?

Michaela

**Comment by nshmyrev** [comment]
You have to change the code to do that probably.

**Comment by mischmerz** [comment]
Thanks again. Are there any plans to add de-reverb to the engine? That *would* be a kicker.

m.

**Comment by morethanuser** [comment]
@mischmerz  have you tried to increase -vad_threshold to something higher than default 3.0? I've got quite good results with -vad_threshold 3.5 and even higher. I also noticed same thing with microphone volume - that needs to be tuned down. I'm using speech recognition with background music on my speakers and have no problems.

**Comment by mischmerz** [comment]
@morethanuser I sure tried. But with high(er) vad levels, pocketshinx tends to gobble up the first syllables  and has problems recognizing short commands ..

**Comment by morethanuser** [comment]
@mischmerz I see. Have you tried to do some echo canceling? Pulseaudio has quite nice working module module-echo-cancel. With one microphone it will work a noise canceler, but if you have two or more you can use beamforming.

https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/Modules/#index45h3

**Comment by morethanuser** [comment]
@mischmerz Teensy Audio Library developers did a quite impressing thing lately - now teensy with audio board can work as USB sound card. So you can hookup mic there and do some preprocessing on Teensy HW. I used this in different project of mine. Just cut down everything below 150hz .. and got better results with music in the background.

**Comment by mischmerz** [comment]
Well .. I find pulseaudio a bit of an overkill for stand-alone, read-only file system raspberry projects. And from what I gathered, the beam forming in pulse-audio is somewhat rudimentary. I tried the new 4-mic re-speaker array which works nicely, but - you know - in the end it all boils down to the trained vocabulary. Sadly, we don't have anything (in the freeware community) that would come even close to what Google and Amazon have. Especially in regard to commands - because the command "lights off" sounds very different to "I asked him to switch the lights off"  - and therefore our engines have problems with short commands.

**Comment by morethanuser** [comment]
@mischmerz I'm using pulseaudio with bananapi M1 and with some little changes in pocketsphinx code I'm able to get response =< 1 second on command recognition (with my postprocessing and TTS response) so for me it's quite ok. I also use bananapi to stream music at the same time, PA cpu usage jumps maybe up to 25%, so it's not bad. I will be releasing this project as opensource (of course) in 2-3 weeks, so maybe you could find there something useful. But from my understanding you want to recognize more natural language than just a set of commands right?

**Comment by dhdaines** [comment]
Hi, this issue isn't relevant to the ASR engine (note that because of CMN, the input volume makes no difference to recognition in general, and AGC has actually never really worked properly in my opinion).  I suggest any audio processing be done prior to feature extraction, this is not something we will support as the way the front-end is written means it would add needless complexity.
