### ISSUE TITLE
ERROR: "acmod.c", line 76: Accoustic Model Definition is not spefified

### ISSUE THREAD

**Issue by steveboatface** [cmusphinx/pocketsphinx#119]
My apologies if this is an obvious answer but after compiling with Visual Studio 2017 and placing both pocketsphinx and sphinxbase to path and running pocketsphinx-continuous i am not able to get it working.

When i try to run in windows powershell the following command with the lm and dic file in the same directory as execution, no matter what i do i get a warner suggesting that my acoustic model definition is not set. How do i set it?

>pocketsphinx_continuous.exe -hmm -inmic yes -lm 0263.lm -dict 0263.dic

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='live', VARNORM='no', AGC='none' ERROR: "acmod.c", line 76: Acoustic model definition is not specified either with -mdef option or with -hmm

**Comment by Viviankps** [comment]
Hi I'm facing the same error too, may I ask how did you solve it? 
Thanks!!

**Comment by Coeur** [comment]
@Viviankps yet, the file is here: https://github.com/cmusphinx/pocketsphinx/blob/master/model/en-us/en-us/mdef
You may not be building from the correct directory.

**Comment by OxMarco** [comment]
Same issue here on Mac OSX
