### ISSUE TITLE
-lm silently wins fight with -jsgf

### ISSUE THREAD

**Issue by gitfoxi** [cmusphinx/pocketsphinx#12]
I guess it doesn't make sense to use both Language model and a grammar. It would be nice if pocketsphinx just refused to do this rather than silently letting the language model win. It's a trap for young players.

**Comment by dhdaines** [comment]
The logic behind all these command line arguments is sick and twisted and not documented, which is a problem.  You can sort of see how it works here: https://github.com/cmusphinx/pocketsphinx/blob/master/src/pocketsphinx.c#L317

As you say, in reality, we should just require the user to select one and only one of `-lm`, `-kws`, `-fsg`, `-jsgf`, etc (there are lots of them).  I'll fix this for the upcoming release (this week I hope).
