### ISSUE TITLE
Question regarding Mandarin acoustic model adaptation

### ISSUE THREAD

**Issue by jhwjhw0123** [cmusphinx/pocketsphinx#120]
Hi, there. I intend to modify the Mandarin acoustic model based on my specific scenario, and I'm following the tutorial and the exemplary files(.filerids and .transcriptions). However, in Mandarin the characters are not naturally separated by spaces. I wonder if I'll be needing to segment the phrases in the .transcriptions file, something like "未来<space> 三天<space> 天气预报". I don't know much about speech recognition, and I know the question might be too simple. But thanks in advance for any helpful comments.

**Comment by nshmyrev** [comment]
You can find good Mandarin databases here:

http://www.openslr.org/33/

http://www.openslr.org/38/

http://www.openslr.org/18/
