### ISSUE TITLE
Including Pocketsphinx Sources In App Directly

### ISSUE THREAD

**Issue by sdliv** [cmusphinx/pocketsphinx#128]
Hi Nshmyrev,

I need some assistance regarding this.  Am I supposed to drag both the sphinxbase and pocketsphinx folders directly into the project?  I'm still struggling to get this working, and I'm not familiar with dragging C code directly into a project I'm using Swift as the language.  Can you provide me detailed steps to directly incorporate the pocketsphinx sources properly into an iOS app?

**Comment by sdliv** [comment]
I've tried this wrapper.  Having trouble installing it because of Swift version mismatch.  Apple, stupidly, doesn't support Swift 2.0 in Xcode 9; and trying to convert their code to 3.0 is extremely tedious.  If there is something I'm missing here that makes that library easy to install, please let me know.

**Comment by sdliv** [comment]
I will try TLSphinx again.

**Comment by mainvolume** [comment]
Believe this branch is swift 3.0 
https://github.com/tryolabs/TLSphinx/tree/add_words_and_code_improvements

**Comment by sdliv** [comment]
I did not see this.  I appreciate it.

**Comment by dhdaines** [comment]
fixed with new build system, more or less
