### ISSUE TITLE
 ( training an acoustic model ) failed to open controle file ...../X_test.fileids no such file or directory at line 89

### ISSUE THREAD

**Issue by lukamodric10** [cmusphinx/pocketsphinx#130]
i am running a new acoustic model on linux i downloaded and instaled :
-pocketsphinx
-sphinxbase
-sphinxtrain
and i created a folder which contains
-etc
-wav
when i run the command to set up my database `sphinxtrain -t arabic setup`
i configure the sphinx_train.cfg file with setting language_model (LM)  line with # since i am using jsgf grammar and not with LM like the following :
~~~
#$DEC_CFG_LANGUAGEMODEL  = "$CFG_BASE_DIR/etc/${CFG_DB_NAME}.lm.DMP";
# Or can be JSGF or FSG too, used if uncommented
$DEC_CFG_GRAMMAR  = "$CFG_BASE_DIR/etc/${CFG_DB_NAME}.jsgf";
# $DEC_CFG_FSG  = "$CFG_BASE_DIR/etc/${CFG_DB_NAME}.fsg";
~~~
and when i run the train this errors show's up
![33776690_1512743762186360_7594837226962288640_n](https://user-images.githubusercontent.com/37020420/40659541-dcf5c670-634e-11e8-8a8b-d2f988d75655.png)
![33692036_1512743448853058_5468199486201266176_n](https://user-images.githubusercontent.com/37020420/40659542-dd37d376-634e-11e8-8624-80d652936e33.png)
![33769797_1512743578853045_1472077771298570240_n](https://user-images.githubusercontent.com/37020420/40659543-dd831980-634e-11e8-8921-0be710215ac0.png)
please help

**Comment by nshmyrev** [comment]
The errors are pretty self-explaining

**Comment by lukamodric10** [comment]
if i found the errors pretty self-explaining then i wouldn't bother to ask my qeustion , i don't understand why !!!
________________________________
De : Nickolay V. Shmyrev <notifications@github.com>
Envoyé : mercredi 30 mai 2018 15:06
À : cmusphinx/pocketsphinx
Cc : lukamodric10; Author
Objet : Re: [cmusphinx/pocketsphinx] ( training an acoustic model ) failed to open controle file ...../X_test.fileids no such file or directory at line 89 (#130)


The errors are pretty self-explaining
