### ISSUE TITLE
Installing an pocketsphinx.egg-info file?

### ISSUE THREAD

**Issue by sthibaul** [cmusphinx/pocketsphinx#136]
Hello,

Running ./configure && make && make install  with today's git results in ./lib/python2.7/site-packages/pocketsphinx being created, but not a pocketsphinx.egg-info file installed. It means that one can't use

    $ python
    >>> from pkg_resources import require
    >>> require("pocketsphinx")

to depend on pocketsphinx, and apparently poses problem to at least some applications (see https://bugs.debian.org/868346).

Samuel

**Comment by sthibaul** [comment]
I don't know either :)

**Comment by dhdaines** [comment]
Using autotools to build python modules is probably not the best idea, we should include a setup.py instead and use that.

**Comment by dhdaines** [comment]
This is fixed in #254 and will be in the next release.
