### ISSUE TITLE
Regression tests failing during installation.

### ISSUE THREAD

**Issue by farkaskid** [cmusphinx/pocketsphinx#137]
All 4 regression tests are failing during the installation. Is this expected..?
Is this a big problem or can it be ignored..?

![screenshot_20180808_150405](https://user-images.githubusercontent.com/16179713/43829479-a8b366c8-9b1c-11e8-9fd7-fbb61f0dd95b.png)
Test log. All 4  are failing due to this reason.

**Comment by farkaskid** [comment]
Continued ignoring the failed tests. Trying [this](https://github.com/xlab/pocketsphinx-go)
![screenshot_20180808_165542](https://user-images.githubusercontent.com/16179713/43834493-eaa99430-9b2b-11e8-975e-a14ccae524df.png)
Now `pkg-config` can't find the `pocketsphinx` package.

**Comment by nshmyrev** [comment]
Closing due to using screenshots with messages. For the future use text and never post screenshots with text.
