### ISSUE TITLE
unable to define correct threshold values

### ISSUE THREAD

**Issue by BakhtawarRehman** [cmusphinx/pocketsphinx#141]
Dear Pocketsphinx fellows,

I am having a probelm with defining right values for keywords threshold. I know it is a tedious work but i am stuck for a couple of days.

The problem is that it kept picking up words even though nobody speak anything. And recognition is not nearly correct even when certain words are spoken.

Words in my dictionary are extremely limited and given below:

```
BACK	B AE K
FORWARD	F AO R W ER D
FULL	F UH L
HALF	HH AE F
LEFT	L EH F T
MOVE	M UW V
RIGHT	R AY T
SPEED	S P IY D
STOP	S T AA P
```

and **kwlist** is:
```
BACK /1e-20/
FORWARD /1e-35/
FULL SPEED /1e-50/
HALF SPEED /1e-50/
LEFT /1e-20/
MOVE /1e-20/
RIGHT /1e-25/
STOP /1e-20/
```

Language model used ia:  https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Indian%20English/

**Comment by nshmyrev** [comment]
https://cmusphinx.github.io/wiki/tutoriallm/#using-keyword-lists-with-pocketsphinx says:

For the best accuracy it is better to have a **keyphrase with 3-4 syllables**. Too short phrases are easily confused.

**Comment by Coeur** [comment]
If I interpret nshmyrev answer correctly, you could, for instance, change your dictionary to:

````
OKBACK	OW K EY B AE K
OKFORWARD	OW K EY F AO R W ER D
OKFULL	OW K EY F UH L
OKHALF	OW K EY HH AE F
OKLEFT	OW K EY L EH F T
OKMOVE	OW K EY M UW V
OKRIGHT	OW K EY R AY T
OKSPEED	OW K EY S P IY D
OKSTOP	OW K EY S T AA P
````
