### ISSUE TITLE
no LiveSpeech

### ISSUE THREAD

**Issue by LavrenkovNV** [cmusphinx/pocketsphinx#155]
root@Dell:/usr/local/lib/python3.6/dist-packages/pocketsphinx# python3 run.py 
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from pocketsphinx import LiveSpeech
ImportError: cannot import name 'LiveSpeech'
root@Dell:/usr/local/lib/python3.6/dist-packages/pocketsphinx# pip3 install pocketsphinx
Requirement already satisfied: pocketsphinx in /usr/local/lib/python3.6/dist-packages (0.1.15)
root@Dell:/usr/local/lib/python3.6/dist-packages/pocketsphinx# 

run.py code:
from pocketsphinx import LiveSpeech
for phrase in LiveSpeech(): print(phrase)

What could be wrong 
help!!!

**Comment by nshmyrev** [comment]
It is not recommended to run python code from the package folders, python can import wrong files from your current folder.
