### ISSUE TITLE
Change some default values in fe.h

### ISSUE THREAD

**Issue by sunliam** [cmusphinx/pocketsphinx#159]
There're many default constant values in fe.h which are important for recognition. My question is that can some of them be modified based on actual input speech data. Take DEFAULT_FRAME_RATE and DEFAULT_WINDOW_LENGTH as examples:

1. DEFAULT_FRAME_RATE is defined as 100. However, the speech FPS is 160 in my case, can I just simply change it to 160?
2. DEFAULT_WINDOW_LENGTH is defined as 0.025625, can I change it to 0.01 which means 10ms ?

**Comment by dhdaines** [comment]
Use the command-line options corresponding to them, which you can see lower down in the file.  These can be stored in a text file called feat.params which you can just pass to sphinx_fe, and include in your model directory - see for example the standard en-us model.
