### ISSUE TITLE
seeed4micvoicecard not working, 16-bit signed PCM: invalid argument (ReSpeaker 4 mic array)

### ISSUE THREAD

**Issue by cipherspec** [cmusphinx/pocketsphinx#161]
I'm trying to test my pocketsphinx installation via:
`src/programs/pocketsphinx_continous -adcdev hw:seeed4micvoicec -inmic yes`

And get the following error:

> Failed to set PCM device to 16-bit signed PCM: invalid argument

arecord -l shows the card as:
`Card 1: seed4micvoicec [seeed-4mic-voicecard], Device 0: bcm2835-i2s-ac10x-codec0`

In /etc/asound.conf it is configured as:
```
[...]
pcm.ac108 {
  type plug
  slave.pcm "hw:seeed4micvoicec"
}
[...]
```

The card / PiHat itself is working fine, I can record sound via:
`arecord -Dac108 -f S32_LE -r 16000 -c 4 out.wav`

Because recording is fine via sample format S32_LE (little endian) for me it looks like I forgot a parameter for pocketsphinx to use this sample format.

Any hints for me?

**Comment by nshmyrev** [comment]
This is an alsa configuration issue, not really a pocketsphinx issue.
