### ISSUE TITLE
segment start_frame and end_frame times are wrong

### ISSUE THREAD

**Issue by wiffleball28** [cmusphinx/pocketsphinx#162]
I upgraded my sphinxbase and pocketsphinx libs and I'm trying to get similar functionality from the libs from version .8.  It doesn't seam possible.  #1 looking to get times for words in segments.  #2 looking to get lattice or word guesses and times.

The resulting segments from python process_raw method have the wrong frame times.  They're off by like 50 seconds.  i'm calling start_utt and end_utt before/after feeding samples.    Possibly the 50 seconds is the time initialize my language models and dictionary?  Using the old decode_raw method times would be offset by 0.  Also after end_utt I would expect the time offset to reset to 0 but it does not. It looks to continue from the last segment.  Maybe i'm missing some reset call?

Also, there does not look to be any way to get at the lattice.  The write_lattice method doesn't look to include probabilities.

**Comment by nshmyrev** [comment]
Decoder.start_stream() would reset times to 0.

For the lattice, I'm not sure about your issue.

**Comment by nshmyrev** [comment]
You have to provide more details - audio file, the code you are using and the log output to get help on this issue.

**Comment by nshmyrev** [comment]
You have to process audio continuously to get proper timing like in https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/continuous_test.py
