### ISSUE TITLE
failing on "recipe for target 'acmod.lo' failed

### ISSUE THREAD

**Issue by andrster** [cmusphinx/pocketsphinx#167]
this occurs after a successful ./autogen.sh and ./configure. I then do the make command. I am running on ubuntu 16.04

**Comment by nshmyrev** [comment]
Same as https://github.com/cmusphinx/pocketsphinx/issues/166

**Comment by andrster** [comment]
does this help?

![screenshot from 2019-02-23 16-08-20](https://user-images.githubusercontent.com/22357321/53531880-9470d600-3ac2-11e9-82b1-2bd6c44ca89c.png)

**Comment by nshmyrev** [comment]
Yes it shows your sphinxbase is outdated
