### ISSUE TITLE
compilation failure due to error "acmod.c:594:9: error: too many arguments to function 'fe_process_frames'"

### ISSUE THREAD

**Issue by krichter722** [cmusphinx/pocketsphinx#17]
2286ecc956e60109d88453ce179fd4d3dc3d098e fails with error `acmod.c:594:9: error: too many arguments to function 'fe_process_frames'` when `make` is run after `./autogen.sh && ./configure`.

The complete log:

    Making all in src
    make[1]: Entering directory '/mnt/richtercloud/sources/pocketsphinx/src'
    Making all in libpocketsphinx
    make[2]: Entering directory '/mnt/richtercloud/sources/pocketsphinx/src/libpocketsphinx'
    /bin/bash ../../libtool  --tag=CC   --mode=compile /usr/bin/gcc -DPACKAGE_NAME=\"pocketsphinx\" -DPACKAGE_TARNAME=\"pocketsphinx\" -DPACKAGE_VERSION=\"5prealpha\" -DPACKAGE_STRING=\"pocketsphinx\ 5prealpha\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LONG_LONG=1 -DSIZEOF_LONG_LONG=8 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PYTHON=\"2.7\" -I.   -I/usr/include/sphinxbase    -I../../include -I../../include -DMODELDIR=\"/usr/local/share/pocketsphinx/model\" -g3 -gdwarf-2 -MT acmod.lo -MD -MP -MF .deps/acmod.Tpo -c -o acmod.lo acmod.c
    libtool: compile:  /usr/bin/gcc -DPACKAGE_NAME=\"pocketsphinx\" -DPACKAGE_TARNAME=\"pocketsphinx\" -DPACKAGE_VERSION=\"5prealpha\" "-DPACKAGE_STRING=\"pocketsphinx 5prealpha\"" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_LONG_LONG=1 -DSIZEOF_LONG_LONG=8 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_PYTHON=\"2.7\" -I. -I/usr/include/sphinxbase -I../../include -I../../include -DMODELDIR=\"/usr/local/share/pocketsphinx/model\" -g3 -gdwarf-2 -MT acmod.lo -MD -MP -MF .deps/acmod.Tpo -c acmod.c  -fPIC -DPIC -o .libs/acmod.o
    acmod.c: In function 'acmod_process_full_raw':
    acmod.c:583:9: error: too many arguments to function 'fe_process_frames'
         if (fe_process_frames(acmod->fe, NULL, inout_n_samps, NULL, &nfr, NULL) < 0)
             ^
    In file included from /usr/include/sphinxbase/feat.h:87:0,
                     from acmod.c:55:
    /usr/include/sphinxbase/fe.h:445:5: note: declared here
     int fe_process_frames(fe_t *fe,
         ^
    acmod.c:594:9: error: too many arguments to function 'fe_process_frames'
         if (fe_process_frames(acmod->fe, inout_raw, inout_n_samps,
             ^
    In file included from /usr/include/sphinxbase/feat.h:87:0,
                     from acmod.c:55:
    /usr/include/sphinxbase/fe.h:445:5: note: declared here
     int fe_process_frames(fe_t *fe,
         ^
    acmod.c: In function 'acmod_process_raw':
    acmod.c:671:17: error: too many arguments to function 'fe_process_frames'
                 if (fe_process_frames(acmod->fe, inout_raw, inout_n_samps,
                     ^
    In file included from /usr/include/sphinxbase/feat.h:87:0,
                     from acmod.c:55:
    /usr/include/sphinxbase/fe.h:445:5: note: declared here
     int fe_process_frames(fe_t *fe,
         ^
    acmod.c:707:13: error: too many arguments to function 'fe_process_frames'
             if (fe_process_frames(acmod->fe, inout_raw, inout_n_samps,
                 ^
    In file included from /usr/include/sphinxbase/feat.h:87:0,
                     from acmod.c:55:
    /usr/include/sphinxbase/fe.h:445:5: note: declared here
     int fe_process_frames(fe_t *fe,
         ^
    Makefile:545: recipe for target 'acmod.lo' failed
    make[2]: *** [acmod.lo] Error 1
    make[2]: Leaving directory '/mnt/richtercloud/sources/pocketsphinx/src/libpocketsphinx'
    Makefile:369: recipe for target 'all-recursive' failed
    make[1]: *** [all-recursive] Error 1
    make[1]: Leaving directory '/mnt/richtercloud/sources/pocketsphinx/src'
    Makefile:463: recipe for target 'all-recursive' failed
    make: *** [all-recursive] Error 1

    MAKE FAILED (exit value 2, total time: 670ms)

**Comment by nshmyrev** [comment]
Remove old sphinxbase package in installed in /usr
