### ISSUE TITLE
Tutorial Code Gives No Output

### ISSUE THREAD

**Issue by ebenz99** [cmusphinx/pocketsphinx#172]
This is code from the tutorial/documentation:

```
from pocketsphinx import LiveSpeech
for phrase in LiveSpeech(): print(phrase)
```

Running on a MacBook Pro. I've tried specifying different microphones, etc, for the constructor and LiveSpeech still outputs nothing to the command line. My mic works totally fine with other speech recognizers, so I'm submitting it here. Is this a bug?

**Comment by nshmyrev** [comment]
Not our tutorial/documentation, sorry.

This is from external repository, it will not work on Mac by default, our examples will.
