### ISSUE TITLE
Dead code in fsg_search.c

### ISSUE THREAD

**Issue by chussong** [cmusphinx/pocketsphinx#177]
I was looking at [fsg_search.c](https://github.com/cmusphinx/pocketsphinx/blob/master/src/libpocketsphinx/fsg_search.c) and I saw there was a bunch of code to handle the `fsgs->bestpath` option but no way for the option to actually be set. It seems that [this commit from 2014](https://github.com/cmusphinx/pocketsphinx/commit/022e7c8303c8273018a3784ae5dd688ca713f1b9#diff-0a0f56e935acd5bbda6202e1e639603f) removed the option-reading code from `fsg_search_init`, but left all the code for *handling* the option in place. Since this commit is from a few months before the GitHub migration, there does not seem to be any record remaining of why it was done.

I have two questions:

1. Why was this option removed? I assume there is some way that it does not make sense to use a lattice for this search?

2. Given that it was removed, can we also remove all of the branches which require it, thereby using `fsg_history_t` for all hypothesizing?

I'll also note that the only way to generate a `ps_lattice_t` from within `fsg_search.c` is via the dead branches, so if it doesn't make sense to use a `ps_lattice_t` we can remove all mention of it from the file. `fsg_search_lattice` (required for the vtable) can return `NULL` like for other searches that don't support lattices.

**Comment by nshmyrev** [comment]
It all can be reenabled but it will be very slow, that issue with slow computation of bestpath for fsg is something to fix. Not sure fsg makes sense at all though, in modern recognizer you do not really need it.

**Comment by chussong** [comment]
How would you feel about reenabling the code but using an `E_WARN` to indicate that it will likely perform badly and its use is discouraged?

I'm also curious what you would recommend using in a modern recognizer for evaluating relative probabilities of a finite, enumerable set of possible transcriptions.

**Comment by nshmyrev** [comment]
> How would you feel about reenabling the code but using an E_WARN to indicate that it will likely perform badly and its use is discouraged?

Thanks, I don't think it is a great idea. Nobody reads those warnings, they just turn off logging by default like in python-pocketsphinx and then send us numerous complains. They can't even read "No such file or directory message"

> I'm also curious what you would recommend using in a modern recognizer for evaluating relative probabilities of a finite, enumerable set of possible transcriptions.

You just list the words you are looking at like "phrase hints" in google. Enforcing order makes things much more complicated. Microsoft has https://docs.microsoft.com/en-us/windows/uwp/design/input/define-custom-recognition-constraints too with a simple lists.

Or I wrote about it once on google+, can't find it. Something like https://cmusphinx.github.io/2014/05/openears-introduces-easy-grammars-for-pocketsphinx/

**Comment by chussong** [comment]
Thank you for the links. The order is indeed important for our application. Perhaps my interpretation is wrong, but it sounds like both of these approaches are using something like a dynamically-generated grammar which would then be run using something like the FSG search, which is what we were intending to do. The Microsoft one even mentions that when given an explicit list, the computation is done locally, which sounds to me like they use HMMs for it too.

I see what you mean about the warnings. In that case, how about adding the option-reading code back in but leaving it commented out, and adding comments to the dead code branches explaining that they're unreachable unless the reading is re-enabled in `fsg_search_init`?

**Comment by nshmyrev** [comment]
> Thank you for the links. The order is indeed important for our application. Perhaps my interpretation is wrong, but it sounds like both of these approaches are using something like a dynamically-generated grammar which would then be run using something like the FSG search, which is what we were intending to do. The Microsoft one even mentions that when given an explicit list, the computation is done locally, which sounds to me like they use HMMs for it too.

For users order is not important, they can say the words in any order, and you need to process them properly. This is not a grammar task to enforce the order

> EDIT: actually, I just remembered that there are already two macros in the file to conditionally enable extra debug information (__FSG_DBG__ and __FSG_DBG_CHAN__). I think adding another one (set by default to 0) around the option-reading code would be a reasonable solution.

If that helps, sure

**Comment by chussong** [comment]
> For users order is not important, they can say the words in any order, and you need to process them properly. This is not a grammar task to enforce the order

I agree that in the vast majority of applications this is true, but we are trying to help non-native users practice saying particular phrases, rather than trying to respond to samples of natural language. In our case I believe the exact phrase, in order (with particular possible deviations around it) is the sensible way to to search.

Thank you again for all your help. I'll submit a pull request shortly.

**Comment by nshmyrev** [comment]
Thank you for the pull request
