### ISSUE TITLE
I have an idea: adjust the sensitivity based on the ambient volume

### ISSUE THREAD

**Issue by andytriboletti** [cmusphinx/pocketsphinx#179]
Hello,
In a phrases.gram file I have:
hey music/1e-15/
heymusic/1e-15/

I am trying to reduce false positives and increase recognition ability. Would it be possible to specify the sensitivity values (in my example 1e-15), dynamically based on the volume of the music playing and other noise in the room. 

One weird way I could do it, would be write to the file after detecting an increase or decrease in volume and maybe run md5 phrases.gram > md5 phrases.gram.md5 on my Android device, but that seems like a lot of work and I don't think it's the right way. Where else would I get started in implementing this idea?

Maybe the sensitivity adjustment based on decibels in the area happens already?

-Andy

**Comment by nshmyrev** [comment]
It is not possible in current framework.

There are many ways to improve recognition and reduce false alarms. Something neural network based like mycroft precise or snowboy can probably help, there are many other projects too.
