### ISSUE TITLE
gstpocketsphinx.c should post messages to the gst bus instead of emitting signals

### ISSUE THREAD

**Issue by ensonic** [cmusphinx/pocketsphinx#18]
signals are not thread safe. SO instead of posting applications messages from  the app
https://github.com/cmusphinx/pocketsphinx/blob/master/src/gst-plugin/livedemo.py#L58

do it like in the gstreamers level or spectrum elements:
http://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/gst/level/gstlevel.c
http://cgit.freedesktop.org/gstreamer/gst-plugins-good/tree/gst/spectrum/gstspectrum.c

If that sounds acceptable to you I can send a PR.

**Comment by nshmyrev** [comment]
This is a great idea, I'd be happy to commit a patch. Thanks!

**Comment by ensonic** [comment]
Nickolay, sorry this took a while. The attached patch works (output at: https://gist.github.com/ensonic/638b6f9886aa1c4dc392), but there are a few places for improvements:
* do you want me to keep the signals? I'd suggest to remove them, but that would break apps that rely on them.
* I added some FIXME: comments
  * the uttid is not extracted from the hypothesis right now and I don't know what the right api for this would be. Can you advice on the API, or should we drop this from the message.
  * would it make sense to add the score to the message?

**Comment by nshmyrev** [comment]
Great, thank you. I'll try to check it in soon.

There is no need to keep signals, we do not care about backward compatibility for now.

Uttid is not used anymore, it's safe to remove it altogether

It would be nice to add result of ps_get_prob to the message, not the score.

**Comment by ensonic** [comment]
Thanks for the reply. I am busy today but I can update the patch with your suggestions tomorrow.

**Comment by ensonic** [comment]
I've updated the PR with your suggestions implemented. Please have a look at the doc blob I wrote for the message. Ideally I'd include something to describe the value range for 'probability' but I have not found anything in the sources. Please also note that in the message I now spell out the keys ('hyp' -> 'hypothesis').

FYI: it looks like some earlier change broke the repo. I need to comment out one line in libpocketsphinx to keep things compiling. This is unrelated to the change I am working on.
``` diff
git diff src/libpocketsphinx/pocketsphinx.c
diff --git a/src/libpocketsphinx/pocketsphinx.c b/src/libpocketsphinx/pocketsphinx.c
index 169285e..f856049 100644
--- a/src/libpocketsphinx/pocketsphinx.c
+++ b/src/libpocketsphinx/pocketsphinx.c
@@ -146,7 +146,7 @@ ps_expand_model_config(ps_decoder_t *ps)
     }
 
     /* Print here because acmod_init might load feat.params file */
-    cmd_ln_print_values_r(ps->config, err_get_logfp(), ps_args());
+    //cmd_ln_print_values_r(ps->config, err_get_logfp(), ps_args());
 }
 
 static void
```

**Comment by ensonic** [comment]
Nevermind, the cmd_ln_print_values_r is the same as in issue #27 and is caused when not building with--libdir=/usr/lib/x86_64-linux-gnu on ubuntu.

**Comment by ensonic** [comment]
@nshmyrev , does the patch look good now? Let me know if you want me to change anything.

**Comment by nshmyrev** [comment]
I applied the patch, thanks a lot for your contribution!
