### ISSUE TITLE
c# wrapper error :The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE' threw an exception.

### ISSUE THREAD

**Issue by waleedmakarem** [cmusphinx/pocketsphinx#180]
I am trying to build C# wrapper to use PocketSphinx into C# enviroment. I am using follow project

https://alphacephei.com/kaldi/PsTest.zip

I have built the Assembly-CSharp.dll. and included it into new VB.net project. when i call below code 
                Dim sr As New Pocketsphinx.Decoder
 i get below error
The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE' threw an exception.

**Comment by nshmyrev** [comment]
Decoder requires config object as an argument, you can check C# sources for details.

**Comment by waleedmakarem** [comment]
Same error when i try to initialize a Config object
   Dim c As Config = Decoder.DefaultConfig()
give this error : 
The type initializer for 'Pocketsphinx.pocketsphinxPINVOKE' threw an exception.
Debug error at below code (Decoder.cs);
  public static Config DefaultConfig() {
    **global::System.IntPtr cPtr = pocketsphinxPINVOKE.Decoder_DefaultConfig();**  <<<<< Error here
    Config ret = (cPtr == global::System.IntPtr.Zero) ? null : new Config(cPtr, true);
    return ret;
  }
