### ISSUE TITLE
Why bin_mdef_free are not exported by default?

### ISSUE THREAD

**Issue by KuribohG** [cmusphinx/pocketsphinx#181]
In bin_mdef.h, the function bin_mdef_free are not tagged as POCKETSPHINX_EXPORT. Why we have some function which create bin_mdef_t object but no function to free them? Is this choice made deliberately?

**Comment by jsalsman** [comment]
The model definitions are not expected to mutate within pocketsphinx invocations, and training, as far as I know, only produces one model as well, so they are probably always freed by exit()

**Comment by nshmyrev** [comment]
Same as https://sourceforge.net/p/cmusphinx/discussion/help/thread/7026dd3f03/
