### ISSUE TITLE
How to silence most prints

### ISSUE THREAD

**Issue by willstout** [cmusphinx/pocketsphinx#182]
There are a lot of pieces of information that get printed that I don't necessarily care about, how can I stop all the 

INFO: ngram_search_fwdflat.c(950):   199022 senones evaluated (913/fr)
INFO: ngram_search_fwdflat.c(952):   299078 channels searched (1371/fr)
INFO: ngram_search_fwdflat.c(954):    17608 words searched (80/fr)
INFO: ngram_search_fwdflat.c(957):    13156 word transitions (60/fr)
etc

from printing?

**Comment by nshmyrev** [comment]
https://stackoverflow.com/questions/17825820/how-do-i-turn-off-e-info-in-pocketsphinx
