### ISSUE TITLE
Pocketsphinx dictionary alternative pronunciations not working 

### ISSUE THREAD

**Issue by kmrosiek** [cmusphinx/pocketsphinx#184]
I am using Pocketsphinx with a dictionary and a keyword list.
I have the word 'cat' in the keyword list:

    cat /1e-1/
I limited the dictionary to list of my words - one of the words is 'cat':

    cat K AE T
I have cat.wav, which says "cat". I try to recognize this wav, but the word cat is not recognized. I run phoneme recognition and it says this wav is represented by:

    K AA
So I want to add this alternative pronunciation to the dictionary:

    cat K AE T
    cat(2) K AA
But, the wav is still not recognized. I replace cats:

    cat K AA
    cat(2) K AE T
Now it works.
Whenever I put brackets next to cat() K AA, this pronunciation is not recognized.
What am I missing? What could be not working?

**Comment by nshmyrev** [comment]
Alternative pronunciations do not work with keyword spotting unfortunately, you have to specify distinct words, probably just by appending modifiers like in a dictionary:

```
cat_1 K AA
cat_2 K AA T
```

and then in keyword list

```
cat_1 /1e-1/
cat_2 /1e-1/
```

And you have to specify all alternative words in keyword list too.

Overall keyword spotting does not work for short words.
