### ISSUE TITLE
[Questions] Max duration of phoneme & phoneme of specific timestamp

### ISSUE THREAD

**Issue by tiancaipipi110** [cmusphinx/pocketsphinx#185]
Have two questions:
1. Say I have generated a phoneme list, how do I go through all the phonemes and get the longest time/duration of a phoneme ?
2. How to get the phoneme of a specific timestamp?

**Comment by nshmyrev** [comment]
You write the code, something like

```
max = -1
for phoneme is phonemes:
      if phoneme.duration > max:
             max = phoneme.duration
return max

```

everything else depends on your programming language etc.
