### ISSUE TITLE
PsTest not working in ios

### ISSUE THREAD

**Issue by Amanpradhan** [cmusphinx/pocketsphinx#186]
I am trying to use [https://alphacephei.com/kaldi/PsTest.zip](url) in ios but I am not getting any word detected, even when my threshold in very low. It works very well in unity editor but how to make it work in ios?

**Comment by nshmyrev** [comment]
You need to check the pocketsphinx output in the logfile to see what happens. File ps.log should be created on the phone.

**Comment by nshmyrev** [comment]
This issue should be reported at https://github.com/cmusphinx/pocketsphinx-unity-demo
