### ISSUE TITLE
Pocketsphinx will crash when user inputs several short speech audio

### ISSUE THREAD

**Issue by ChankiWu** [cmusphinx/pocketsphinx#188]
I used Bazel C++ to develop Pocketsphinx and we recently find it will crash when we input several short speech audios such as continually sending vert short empty audio. And the error is 

`src/libpocketsphinx/ngram_search_fwdtree.c:658: eval_word_chan: Assertion `bitvec_is_set(ngs->word_active, w)' failed.Aborted (core dumped)`

Besides, this error will both appear in Linux C++ and Android platforms. 

Thanks.

**Comment by nshmyrev** [comment]
Try kaldi android
