### ISSUE TITLE
Pocketsphinx install on raspbian buster fails

### ISSUE THREAD

**Issue by muddyknee** [cmusphinx/pocketsphinx#189]
Pulseaudio (see error message below) not used - using alsa - I used the version on piwheels.
I've used it okay on earlier raspbian versions.
 
   swig/sphinxbase/ad_pulse_wrap.c: In function ‘_wrap_Ad_readinto’:
    swig/sphinxbase/ad_pulse_wrap.c:3735:5: warning: ‘PyObject_AsWriteBuffer’ is deprecated [-Wdeprecated-declarations]
         res2 = PyObject_AsWriteBuffer(obj1, &buf2, &size2);
         ^~~~
    In file included from /usr/include/python3.7m/Python.h:147,
                     from swig/sphinxbase/ad_pulse_wrap.c:150:
    /usr/include/python3.7m/abstract.h:500:17: note: declared here
     PyAPI_FUNC(int) PyObject_AsWriteBuffer(PyObject *obj,
                     ^~~~~~~~~~~~~~~~~~~~~~
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DSPHINXBASE_EXPORTS -DPOCKETSPHINX_EXPORTS -DSPHINX_DLL -DHAVE_CONFIG_H -Ideps/sphinxbase/include -Ideps/sphinxbase/include/sphinxbase -Ideps/sphinxbase/include/android -I/usr/include/python3.7m -c deps/sphinxbase/src/libsphinxad/ad_pulse.c -o build/temp.linux-armv7l-3.7/deps/sphinxbase/src/libsphinxad/ad_pulse.o -Wno-unused-label -Wno-strict-prototypes -Wno-parentheses -Wno-unused-but-set-variable -Wno-unused-variable -Wno-unused-result -Wno-sign-compare -Wno-misleading-indentation
    deps/sphinxbase/src/libsphinxad/ad_pulse.c:44:10: fatal error: pulse/pulseaudio.h: No such file or directory
     #include <pulse/pulseaudio.h>
              ^~~~~~~~~~~~~~~~~~~~
    compilation terminated.
    error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
    
    ----------------------------------------

**Comment by nshmyrev** [comment]
You need to install libpulseaudio-dev package.
