### ISSUE TITLE
Unable to change lmname when pocketsphinx is running

### ISSUE THREAD

**Issue by benoitfragit** [cmusphinx/pocketsphinx#19]
I'm currently developing a python package VOXGenerator to control your desktop. I'm facing trouble because I'm using the gst plugin in python everything work well so I manage to improve recognition by using a set of small language models. Thanks to some activation function i'm trying to change the current lmname with :

sphinx.set_property('lmname', new_lm_name) 

But this hasn't got any effect when the piprline is running.

**Comment by nshmyrev** [comment]
Simple changing the property should not change anything indeed. There is a special «configured» property to apply the changes. Please try to call

set_property(«configured", True)

to finalize the cofiguration
