### ISSUE TITLE
Listening and Recognizing function takes more time to execute

### ISSUE THREAD

**Issue by srigandeswaran** [cmusphinx/pocketsphinx#190]
Hi all,
Iam using Pocketsphinx code integrated with the c code, when I try to call pocketsphinx code from my main code the listening function takes more time to listen and recognizing function too takes more time to give the final output string.

is there any parameters to reduce the time consumption that the two function takes?
Waiting for the better solution and please do the need.

Thanks in advance.

**Comment by nshmyrev** [comment]
Time to learn about threading.

**Comment by srigandeswaran** [comment]
@nshmyrev 
We know how thread executes and even sometimes while running sphinx code separately it is taking more time to execute the 
LISTENING
RECOGNIZING
functions.
**The question is there any way to reduce the time consumption that these function takes?l**ike arguments or parameters
