### ISSUE TITLE
#include <sphinx_config.h> No file Assembly instructions small

### ISSUE THREAD

**Issue by KenyaLS** [cmusphinx/pocketsphinx#192]
#include <sphinx_config.h> No file Assembly instructions small
![image](https://user-images.githubusercontent.com/20774076/73140160-82633300-4097-11ea-8947-f19ab641dd26.png)

**Comment by nshmyrev** [comment]
The folder with sphinx_config should be in include directories in project properties, not sure why you miss it, it should be there by default.
