### ISSUE TITLE
Segmentation fault when using ps_reinit

### ISSUE THREAD

**Issue by benoitfragit** [cmusphinx/pocketsphinx#20]
When I Use ps_reinit I Always have a segmentation fault

**Comment by benoitfragit** [comment]
For people who try to dynamically switch the lmname. I succeed in my research by adding a little fix in gstpocketsphinx.c 

Please don't call the ps_reinit function it leads to a seg fault !

At the line 464 of the gstpocketsphinx.c you should do :+1: 

``` C
    case PROP_LM_NAME:
        gst_pocketsphinx_set_string(ps, "-fsg", NULL);
        gst_pocketsphinx_set_string(ps, "-lmname", value);
        if (value != NULL && ps->ps)
        {
            ps_set_search(ps->ps, g_strdup(g_value_get_string(value)));
        }
```

It works and it is awesome, can you add this fix or no

**Comment by nshmyrev** [comment]
I've committed slightly updated fix, now it should both properly work on configured and switch lmname as you suggested. 

One note about your proposal, you do not need g_strdup here, it will cause a memory leak.

**Comment by benoitfragit** [comment]
Ok I've updated and it works thank you
