### ISSUE TITLE
cmake-js not found

### ISSUE THREAD

**Issue by benbucksch** [cmusphinx/pocketsphinx#200]
Reproduction:
* `yarn add pocketsphinx`

Actual result:
* **Build failure**
* `/bin/sh: 1: cmake-js: not found`

Expected result:
* `cmake-js` is a dependency
* `cmake-js` is called as `.node_modules/cmake-js/bin/cmake-js` instead of just `cmake-js`, and not expected in `/usr/local/bin/` as a global system command. This will also resolve the problem that cmake-js in turn depends on npmlog etc..

**Comment by benbucksch** [comment]
The issue is much bigger, see #201

**Comment by dhdaines** [comment]
Sadly I will close this because binding C to JavaScript in Node.js won't be supported in the future.
