### ISSUE TITLE
Automated build not working

### ISSUE THREAD

**Issue by benbucksch** [cmusphinx/pocketsphinx#201]
Reproduction:
* `yarn add wakeword`

Actual result:
* As part of the dependencies, it pulls module `pocketsphinx`, which wants to build native executables.
* This build fails with obscure errors. Once you fixed one error, (e.g. #200), another build error comes. To be followed by another.
* The dependencies are documented on https://www.npmjs.com/package/pocketsphinx , but that's not suitable for users, because not automated. No user will manually compile and install these packages, one after the other. This is particularly true for a library package like this one that's used as a part of a larger program.

Expected result:
* All build dependencies are automatically installed and built.
* If OS level dependencies are required, then the build should make specific checks before starting to build, whether the dependencies are met (instead of failures during compile). If dependencies are not met, it should print a clear message (**not** obscure errors about downfall symptoms) and explain which programs need to be installed, and it should give the exact `apt install` command for Ubuntu/Debian and likewise for Fedora/Redhat, at the very least.
* Everything else should be built 100% automated.

Importance:
* With a manual compile ordeal, the npm package is unsuitable for use within larger programs. However, that's the whole point of pocketsphinx (as it's useful on its own) and of npm modules.

**Comment by nshmyrev** [comment]
Well, pocketsphinx is not really a priority these days, we are working on vosk-api. 

As for making everything buildable on NPM, thats kinda hard because of all the dependencies. It is not really a great idea to support another complicated build system. 

NPM works for pure js libraries or for very simple native modules. Not easy to make it work for complex build process like pocketsphinx has.

**Comment by dhdaines** [comment]
I agree with @nshmyrev, NPM is not a very well designed system for complex builds.  For my part I don't really want to support binding C to JavaScript, it is preferable to do pure javascript or WebAssembly.
