### ISSUE TITLE
Assertion while reading tmat file

### ISSUE THREAD

**Issue by Molochnik** [cmusphinx/pocketsphinx#205]
I tried to use Russian recognition using the dictionary and models from this [link](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Russian/)
but `tmat_init()` always throws assertiion when calling `bio_readhdr()`:

![Снимок](https://user-images.githubusercontent.com/22855207/78746428-7cc77a80-796f-11ea-97df-208cf6de4fee.PNG)

**Comment by nshmyrev** [comment]
Same as https://stackoverflow.com/questions/60953096/installing-pocketsphinx-on-windows-10
