### ISSUE TITLE
ngram_model_read infinite loop?

### ISSUE THREAD

**Issue by Molochnik** [cmusphinx/pocketsphinx#206]
`pocketsphinx_continioues` doesn't return from calling `ngram_model_read`, the output window:

![Снимок](https://user-images.githubusercontent.com/22855207/78759187-e9e70a00-7987-11ea-8143-7314657143d9.PNG)

This output has been produced after I changed code generation from MTd to MD as been offered for both sphinxbase, pocketsphinx and pocketsphinx_continioues and then debugged it on a test file from Russian dictionary with these arguments:
"-infile C:\CT\zero_ru_cont_8k_v3\test.wav -hmm C:\CT\zero_ru_cont_8k_v3\zero_ru.cd_cont_4000\ -dict C:\CT\zero_ru_cont_8k_v3\ru.dic -lm C:\CT\zero_ru_cont_8k_v3\ru.lm -remove_noise no"

**Comment by nshmyrev** [comment]
Try with https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Russian/cmusphinx-ru-5.2.tar.gz/download.

**Comment by Molochnik** [comment]
All right, tested, same test file, new language directory and files.
Arguments
-infile C:\CT\zero_ru_cont_8k_v3\test.wav -hmm C:\CT\cmusphinx-ru-5.2\ -dict C:\CT\cmusphinx-ru-5.2\ru.dic -lm C:\CT\cmusphinx-ru-5.2\ru.lm -remove_noise no

The result is the same BUT I decided to wait and after around 60 seconds new log appeared "Training quantizer", and then after 30 more seconds the program exits with result 0 and no output result. Then I retested the 1st example - it worked the same way, I just didn't wait for so long. Final output window:
![Снимок2](https://user-images.githubusercontent.com/22855207/78765839-35ea7c80-7991-11ea-82c5-98d550960529.PNG)
Audio file was taken from zero_ru_cont_8k_v3 and renamed to test.wav and looks normal:
![image](https://user-images.githubusercontent.com/22855207/78766454-f3756f80-7991-11ea-9e6a-23a3a2d1eef4.png)

**Comment by nshmyrev** [comment]
> The result is the same BUT I decided to wait and after around 60 seconds new log appeared

Looks like your CPU is very slow.

>  Final output window:

It is the output from zero-ru, not cmusphinx-ru.

> Audio file was taken from zero_ru_cont_8k_v3 and renamed to test.wav and looks normal:

For cmusphinx-ru audio file should be 16khz.

For zero-ru you also need to add -samprate 8000 to command line to decode 8khz file.

If you compiled recent github clone you should have seen a message, looks like you compiled very old version.

```
ERROR: "continuous.c", line 136: Input audio file has sample rate [8000], but decoder expects [16000]
FATAL: "continuous.c", line 165: Failed to process file 'decoder-test.wav' due to format mismatch.

```

**Comment by nshmyrev** [comment]
Also it might be slow because you compiled with debug runtime. You should try with MT runtime, the problem is to make sure that runtime is consistent in pocketsphinx and sphinxbase.

**Comment by Molochnik** [comment]
Latest results:
1) I downloaded 2020 sources both for pocketsphinx and sphinxbase
2) All exceptions and assertions are disappeared
3) test.was from zero_ru_cont_8k_v3.tar.gz has improper WAV format (8 kHz instead of 16 kHz)
4) When code generation is set to MT, all process of recognizing of a proper small audio file takes about 30 seconds.
5) I have a good PC notebook i7-7700 2.8 kHz, 32 GB RAM
6) Almost all the time (30 s) is consumed by `ngram_model_read` though I didn't specify grammar file (20 s before "Training quantizer" message and 10 s after).
7) The process of recognizing of the voice file itself takes almost nothing after grammar is loaded
8) MSVC console doesn't show UTF-8 string properly so I added `SetConsoleOutputCP(CP_UTF8);` right before `printf("%s\n", hyp);`
9) The result of the program is almost perfect "авторизации прошла успешно" instead of "авторизация прошла успешно" 
10) Thanks!

**Comment by nshmyrev** [comment]
Ok. You are welcome to try vosk-api too.

**Comment by Molochnik** [comment]
Ok, I'll do. By the way is it possible not to load grammar at all for recognizing of the simple sentences? Also I couldn't find anywhere a Russian grammar file (-jsgf). Is not required?
