### ISSUE TITLE
Some small issues

### ISSUE THREAD

**Issue by Molochnik** [cmusphinx/pocketsphinx#208]
1) 	continuous.c, batch.c, gstpocketsphinx.c
config is freed 2 times while executing this code:
```
    ps_free(ps);
    cmd_ln_free_r(config);
```
2) If you recognize several different audio files during a single `ps_decoder_t` session and then recognize them again you'll get slightly different results for the same file (even though the buffers are cleared, `ps_start_utt` and `ps_end_utt` are called for each file).
3) why not to move `recognize_from_file() `and `recognize_from_microphone()` to pocketsphinx? These functions are very useful.
4) why not to add sources from sphinxbase (52 src files) directly to pocketsphinx? If added you will no longer need sphinxbase.dll and you will no longer need to worry about "code generation" prefixes (all of them will work the same, now - only those that use shared memory manager)

**Comment by nshmyrev** [comment]
> config is freed 2 times while executing this code:

It is unreferenced first, then released. So it should be ok

> If you recognize several different audio files during a single ps_decoder_t session and then recognize them again you'll get slightly different results for the same file (even though the buffers are cleared, ps_start_utt and ps_end_utt are called for each file).

Yes, there is some internal state for denoising. You should probably call `ps_start_stream`. And there is dither too.

> why not to move recognize_from_file() and recognize_from_microphone() to pocketsphinx? These functions are very useful.

We never thought about it.

> why not to add sources from sphinxbase (52 src files) directly to pocketsphinx? If added you will no longer need sphinxbase.dll and you will no longer need to worry about "code generation" prefixes (all of them will work the same, now - only those that use shared memory manager)

Back in 90s it was popular to have modular packages so you don't have install dependencies if you don't need them. And there were sphinx3 and sphinx2 and decoders which depend on sphinxbase. I agree it would be nicer to have a single package but it is not relevant these days anymore when sphinx is not really developed actively.

**Comment by Molochnik** [comment]
Ok, got, thanks!
