### ISSUE TITLE
Couldn't find a whole package with English lang

### ISSUE THREAD

**Issue by Molochnik** [cmusphinx/pocketsphinx#209]
I could not find a proper package that contains all required files for the English language. I downloaded all the files from [lm and acoustic models](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English/) but they all seem don't work with this dictionary. All I see is a lot of "hmm"s. Could you please help me to find the right ones?

**Comment by nshmyrev** [comment]
> work with this dictionary

With which dictionary models doesn't work? Models are included by default in pocketsphinx sources, including working [cmudict](https://github.com/cmusphinx/pocketsphinx/blob/master/model/en-us/cmudict-en-us.dict).
