### ISSUE TITLE
stops working after an hour or so

### ISSUE THREAD

**Issue by MikeyBeez** [cmusphinx/pocketsphinx#210]
I'm using pocketspinx with uberi speechrecognition.  After about an hour, pocketspinx stops working, and I have to close my terminal.
I'm on Ubuntu 18.04.  I built sphinxbase and pocketshpinx from source yesterday.

**Comment by nshmyrev** [comment]
Pocketsphinx is not supported anymore. Try https://github.com/alphacep/vosk-api.

uberi speechrecognition is a bad idea since it doesn't support streaming.
