### ISSUE TITLE
Problem with PocketSphinx on Raspberry Pi 4B and Python 3.7

### ISSUE THREAD

**Issue by fabssssss** [cmusphinx/pocketsphinx#211]
Hi,

I am trying to develop a Speech recognition system with my Raspberry Pi 4B using PocketSPhinx and Python 3.7.3.

`import sys,os
import pyaudio
import wave

def decodeSpeech(hmmd,lmdir,dictpp,wavfile):
    import pocketsphinx as ps
    import sphinxbase
    
    config = ps.Decoder.default_config()
    config.set_string('-hmm', hmmd)
    config.set_string('-lm', lmdir)
    config.set_string('-dict', dictpp)
    
    speechRec = ps.Decoder(config)    **# ERROR LINE !**

    wavFile = file(wavfile,'rb')
    wavFile.seek(44)
    speechRec.decode_raw(wavFile)
    result = speechRec.get_hyp()
    return result[0]

hmdir = "/home/pi/.local/lib/python3.7/site-packages/pocketsphinx/model/FR"
lmd = "/home/pi/.local/lib/python3.7/site-packages/pocketsphinx/model/french3g62K.lm.dmp"
dictp = "/home/pi/.local/lib/python3.7/site-packages/pocketsphinx/model/frenchWords62K.dic"
wavefile = "/home/pi/.local/lib/python3.7/site-packages/pocketsphinx/data/o0.wav"

recognised = decodeSpeech(hmdir,lmd,dictp,wavefile)

print (recognised)
cm = 'espeak "'+recognised+'"'
os.system(cm)`

I am able to record WAV files with my mic, but I have issues with the configuration of the decoder:
In the 'decodeSpeech' function above, the program stops at ps.Decoder(config) (the line tagged # ERROR ).
The program blocks in this line for 5 minutes and then I have the error code:

`Traceback (most recent call last):
  File "/home/pi/Documents/Programmes/sr2bis.py", line 29, in <module>
    recognised = decodeSpeech(hmdir,lmd,dictp,wavefile)
  File "/home/pi/Documents/Programmes/sr2bis.py", line 15, in decodeSpeech
    speechRec = ps.Decoder(config)    # ERROR LINE !
  File "/home/pi/.local/lib/python3.7/site-packages/pocketsphinx/pocketsphinx.py", line 273, in __init__
    this = _pocketsphinx.new_Decoder(*args)
RuntimeError: new_Decoder returned -1`

Thanks if you have any idea!

**Comment by nshmyrev** [comment]
Thats gonna be very slow and not gonna work. You can try https://github.com/alphacep/vosk-api with French model from https://github.com/alphacep/kaldi-android-demo/releases/download/2020-01/alphacep-model-android-fr-pguyot-0.3.tar.gz

**Comment by fabssssss** [comment]
Really too slow ... even with a RPI 4b with 4Go?
OK, I am going to try vosk!
Thx :-)

**Comment by fabssssss** [comment]
Works quite well! Thx for that. Now continuing my tests.
