### ISSUE TITLE
question(quality): PocketSphinx live speech recognition in the real practice usage

### ISSUE THREAD

**Issue by Kristinita** [cmusphinx/pocketsphinx#213]
### 1. Summary

I get bad results for Russian language speech recognition. The percentage of PocketSphinx errors is too large to be used in practice.

Can I improve PocketSphinx speech recognition quality (use methods are described in “[**Adapting the default acoustic model**](https://cmusphinx.github.io/wiki/tutorialadapt/)”, “[**Tuning speech recognition accuracy**](https://cmusphinx.github.io/wiki/tutorialtuning/)” or maybe any another), so that the recognition quality is comparable to the [**Web Speech API**](https://www.google.com/intl/en/chrome/demos/speech.html)?

### 2. Usage

I use speech recognition instead of writing of questions for trainings in Russian-language intellectual games like “[**What? Where? When?**](https://en.wikipedia.org/wiki/What%3F_Where%3F_When%3F)” and “[**Brain-ring**](https://ru.wikipedia.org/wiki/%D0%91%D1%80%D0%B5%D0%B9%D0%BD-%D1%80%D0%B8%D0%BD%D0%B3)” (see “Steps to reproduce” section). I look at the recognized text, if I forgot something in the spoken question.

I get not ideal, but acceptable recognition in Web Speech API and horrible results for PocketSphinx.

Example below:

### 3. Steps to reproduce

I held my microphone up to the PC speaker → I played first 17 seconds of [**this video**](https://www.youtube.com/watch?v=bqrYgR36wwo). The spoken text:

> Дорогие телезрители, добрый вечер. Сегодня суббота, 4 января. Через несколько минут начнётся главная игра сезона 2019 года. Возможно, сегодня мы узнаем имя нового кавалера ордена Совы. Итак, начинаем!

#### 4.1. PocketSphinx

> говорите зрители добрый вечер сегодня суббота четвёртая марта м через несколько минут насчёт заглавная разумом облепихи чаем девятнадцатого

or

> да и телезрители добрый вечер сегодня суббота четвёртая марта через несколько минут начал заглавная названо де сейчас дилетантством

It's not good. From this, it is difficult to understand the real text.

#### 4.2. Web Speech API

I don't change volume and the relative position of my microphone and computer speaker.

> Родители зрителя Добрый вечер сегодня суббота 4 января через несколько минут начнется главный игра сезона 2019 года возможно сегодня мы узнаем имя нового кавалера ордена славы и Так начинаем

Not amazing, but this can be used in practice.

#### 5.1. Hardware

1. [**Razer Seiren Elite**](https://www.razer.com/gaming-broadcaster/razer-seiren-elite) microphone

#### 5.2. Software

1. Windows 10.0.18363 Pro N for Workstations 64-bit EN
1. Python 3.8.2
1. pip 20.0.2
1. SpeechRecognition 3.8.1
1. PocketSphinx 0.1.15
1. PyAudio 0.2.11

#### 5.3. Installation

1. [**PocketSphinx**](https://stackoverflow.com/a/61527714/5951529)
1. [**PyAudio**](https://stackoverflow.com/a/59296516/5951529)

#### 5.4. Configuration

1. I configure Russian language for SpeechRecognition in the same way as described [**here**](https://github.com/Uberi/speech_recognition/issues/192#issuecomment-270227681).

#### 5.5. Script

[**From SpeechRecognition examples**](https://github.com/Uberi/speech_recognition/blob/fed05fec2668fd3ed44aea8c03978b6dcbff8b0b/examples/microphone_recognition.py#L1-L19):

```python
# !/usr/bin/env python3

# NOTE: this example requires PyAudio because it uses the Microphone class

import speech_recognition as sr

# obtain audio from the microphone
r = sr.Recognizer()
with sr.Microphone() as source:
    print("Say something!")
    audio = r.listen(source)

# recognize speech using Sphinx
try:
    print("Sphinx thinks you said " + r.recognize_sphinx(audio))
except sr.UnknownValueError:
    print("Sphinx could not understand audio")
except sr.RequestError as e:
    print("Sphinx error; {0}".format(e))
```

Thanks.

**Comment by nshmyrev** [comment]
Pocketsphinx is pretty old technology.

You can try https://github.com/alphacep/vosk-api, in particular https://github.com/alphacep/vosk-server.

**Comment by Kristinita** [comment]
@nshmyrev , I'm not sure, that this closing this issue is better and user-friendly solution.

1. I don't find any information in documentation, that PocketSphinx is deprecated, no longer maintained software or that some types of issues will closed or something like that. In this case, quick closing issues without substantive consideration means, that users wasted their time for issue details.
1. New PocketSphinx users can have same or similar problem. But in documentation and/or opened issues are not described this possible problem. Users can spend a lot of time installing and configuring PocketSphinx, and then get result not applicable in real practice. I don't think, that it good.

(Also, I'm already waiting for Windows support of vosk-api)

Thanks.
