### ISSUE TITLE
Getting 100% error rate while training CMUSphinx acoustic model, what am I doing wrong?

### ISSUE THREAD

**Issue by abhidaberao** [cmusphinx/pocketsphinx#219]
I am building a speaker independent spoken digit recognition model with CMUSphinx.

I used the dataset from [Wolfram Repository][1] (The dataset is a subset of the Speech Commands Dataset v0.01 released by Google).

I am getting a 100% Sentence and 100% Word Error Rate.
What am I doing wrong? I am completely new to this. please help.

`MODULE: DECODE Decoding using models previously trained
        Decoding 2362 segments starting at 0 (part 1 of 1) 
        0% 
        Aligning results to find error rate
        SENTENCE ERROR: 100.0% (2362/2362)   WORD ERROR RATE: 100.0% (2362/2362)
`

Maybe the problem is in my sphinx_train.cfg.
[sphinx_train.cfg](https://github.com/abhidaberao/Text-Prompted-Speaker-Verification-using-CMUSphinx/blob/master/etc/sphinx_train.cfg)

Or you may want to look at all other files.
[Complete /etc folder](https://github.com/abhidaberao/Text-Prompted-Speaker-Verification-using-CMUSphinx/tree/master/etc)

**Comment by nshmyrev** [comment]
words case mismatch in dictionary and lm
