### ISSUE TITLE
Latest API or Documentation?

### ISSUE THREAD

**Issue by benjgorman** [cmusphinx/pocketsphinx#22]
Hi I'm looking for the latest documentation or API for pocketsphinx/sphinxbase? All I can find are these:

http://cmusphinx.sourceforge.net/doc/pocketsphinx/
http://cmusphinx.sourceforge.net/doc/sphinxbase/

Which appear to be from 2014, is this the latest?

I have it installed under XCode6.

Cheers

**Comment by nshmyrev** [comment]
I've updated the API docs on site, thank you for the report.

Pocketsphinx uses doxygen for documentation, so latest documentation is compiled when you build sources.
