### ISSUE TITLE
Unused function warnings from swig makefile

### ISSUE THREAD

**Issue by tushardhoot** [cmusphinx/pocketsphinx#23]
Hi,

Making Java interfaces with the makefile in /swig/java/ currently generates a lot of unnecessary "SWIG_* defined but not used" warnings. Just wondering if the `-Wno-unused-function` flag was left off unintentionally or if this is a legitimate error?

(this is using the /swig/java folder with the current release of pocketsphinx [pocketsphinx5-prealpha]).

Thanks!

**Comment by nshmyrev** [comment]
Fixed in trunk, thank you for the report
