### ISSUE TITLE
Low accuracy on the pretrained english model

### ISSUE THREAD

**Issue by DereWah** [cmusphinx/pocketsphinx#230]
Hello, I tried using pocketsphinx with the speech_recognition python package, but I am getting a really really low accuracy. Even just saying "Hello" is picked up as something totally different. I am using the english model included in the pocketsphinx download.

**Comment by nshmyrev** [comment]
Pocketsphinx is very old technology, it is not very accurate. You can try Vosk for example, it should be much more accurate.

**Comment by DereWah** [comment]
Uh okay, thank you :)
