### ISSUE TITLE
What's the difference between pocketsphinx and vosk?

### ISSUE THREAD

**Issue by youngstu** [cmusphinx/pocketsphinx#233]
What's the difference between pocketsphinx and vosk?

**Comment by dhdaines** [comment]
Perhaps @nshmyrev can answer for vosk :)

PocketSphinx is a now rather old and obsolete system, which people nonetheless seem to use a lot.  It is not very good for large-vocabulary continuous speech recognition but can still be interesting for some tasks.

**Comment by PatMyron** [comment]
> old and obsolete system, which people nonetheless seem to use a lot

I'd consider pinning this issue and updating the repo and org descriptions and these:
https://cmusphinx.github.io/
https://en.wikipedia.org/wiki/CMU_Sphinx

These comments are buried for recommending users use another Github org:
https://github.com/cmusphinx/pocketsphinx-android/issues/58#issuecomment-1119431334
