### ISSUE TITLE
Can pocksphinx support single Chinese word alignment?

### ISSUE THREAD

**Issue by youngstu** [cmusphinx/pocketsphinx#234]
Can pocksphinx support single Chinese word alignment?

**Comment by dhdaines** [comment]
It should work, provided the acoustic model is good enough and matched to your input :)  Currently there are some Mandarin acoustic models at https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/ and we will move them to github soon.

Alignment is best done by creating a finite-state grammar with the expected word or sentence and "decoding" with it.
