### ISSUE TITLE
Error opening audio device (null) for capture: Connection refused

### ISSUE THREAD

**Issue by hackebike** [cmusphinx/pocketsphinx#238]
I testing on a Raspberry PI 4 8Gb 64 bit OS beta Kernel 5.10
I am the seeedstudio 4 mic ReSpeaker hat on it and mics works fine with SpeechRecognition and other Speech Rec packages.

I compiled the **pocketsphinx-5prealpha** and **sphinxbase-5prealpha** everything is fine, than I tried to run:

`sudo pocketsphinx_continuous -lm 3963.lm -dict 3963.dic -verbose yes -fwdtree no -fsgusefiller no -round_filters no -topn 1 -ds 2 -maxwpf 5 -beam 1 -lpbeam 1 -logfn /dev/null -inmic yes`

I get this error:
**Error opening audio device (null) for capture: Connection refused**

Any ideas?

The command: ```
arecord -L
null
    Discard all samples (playback) or generate zero samples (capture)
jack
    JACK Audio Connection Kit
pulse
    PulseAudio Sound Server
default
playback
ac108
usbstream:CARD=b1
    bcm2835 HDMI 1
    USB Stream Output
usbstream:CARD=Headphones
    bcm2835 Headphones
    USB Stream Output
sysdefault:CARD=seeed4micvoicec
    seeed-4mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0
    Default Audio Device
dmix:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0
    Direct sample mixing device
dsnoop:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0
    Direct sample snooping device
hw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0
    Direct hardware device without any conversions
plughw:CARD=seeed4micvoicec,DEV=0
    seeed-4mic-voicecard, bcm2835-i2s-ac10x-codec0 ac10x-codec.1-003b-0
    Hardware device with all software conversions
usbstream:CARD=seeed4micvoicec
    seeed-4mic-voicecard
    USB Stream Output

```

**Comment by dhdaines** [comment]
Hello, I realize this is not a nice way to close a bug, but the audio library in SphinxBase was sufficiently buggy and badly designed that it has simply been removed.  It is preferable to connect to the audio yourself and pass the raw data (we now support int16 and float32, incidentally) to PocketSphinx directly.
