### ISSUE TITLE
语音唤醒很容易“误触”，如何避免？

### ISSUE THREAD

**Issue by hcsaaron** [cmusphinx/pocketsphinx#239]
我自己训练了小词汇语言模型
xiaoan.dict如下：
小安小安 x iao as an x iao as an
你好小安 n i h ao x iao as an

仅包含两个词汇。

同时也调整了中文声学模型。

但使用时很容易“误触”，例如我说“小度小度”或“小黑小黑”，会识别出“小安小安”；或者说“你好你好”时，会识别出“你好小安”。这不是我想要的，我希望除了我设定的关键词，说其他词不要触发，毕竟它们发音区别还是很大的，我想不应该会触发才对呀。

请问是我该如何优化？

这是我自己调整的中文模型：
[xiaoan.zip](https://github.com/cmusphinx/pocketsphinx/files/6150335/xiaoan.zip)

**Comment by dhdaines** [comment]
Hello!  Sorry but my Chinese is not very good so I will reply in English.  Unfortunately it is difficult to debug modeling issues of this kind, and the results when there is a mismatch between the input and the dictionary can be unpredictable.  You can try to use a wider beam (-beam, -wbeam, -pbeam settings to 1e-100 for example).
