### ISSUE TITLE
build for iphone

### ISSUE THREAD

**Issue by RlabFPT** [cmusphinx/pocketsphinx#24]
i run ./build_iphone.sh 

/pocketsphinx/src/libpocketsphinx/ptm_mgau.c:51:10: fatal error: 
      'sphinx_config.h' file not found
#include <sphinx_config.h>
         ^
/pocketsphinx/src/libpocketsphinx/s2_semi_mgau.c:51:10: fatal error: 
      'sphinx_config.h' file not found
#include <sphinx_config.h>

How can i fix it? Plz help me. thanks

**Comment by nshmyrev** [comment]
First of all learn to report issues in proper package

**Comment by DanielAsher** [comment]
try https://github.com/tryolabs/TLSphinx.git
