### ISSUE TITLE
Autogen build on Windows 10/Msys2 MinGW 64

### ISSUE THREAD

**Issue by n0dus** [cmusphinx/pocketsphinx#248]
Building pocketsphinx 5prealpha on Windows 10 using Msys2 system with MinGW 64 gives Makefiles containing the following lines:

**SWIG_LIB = C:\msys64\mingw64\bin\Lib
C:/msys64/mingw64/share/swig/4.0.2**

Trying to build the system using "make" results in the following error:

**Makefile: 312: *** missing separator.  Stop.**

Replacing the newline by a space fixes the problem.

This issue affects all Makefiles in all CMU Sphinx related projects (also sphinxbase etc.).

**Comment by dhdaines** [comment]
Hi, I just completely changed the build system to use CMake now.  It seems to mostly work for me in VSCode and with NMake, haven't tried it with MSYS2 though.  If you have a moment to try this PR let me know: https://github.com/cmusphinx/pocketsphinx/pull/251

**Comment by n0dus** [comment]
I tried PR #250 that included the new CMake system and it worked.
I have used cmake-gui to set up the Makefiles since the built-in cmake of Msys2 tends to not find the correct tool chain.

The Swig problem is effectively gone, also the build process seems much faster. Thanks!
