### ISSUE TITLE
Problems with gstreamer-1.0

### ISSUE THREAD

**Issue by benoitfragit** [cmusphinx/pocketsphinx#25]
I've tried to migrate a pipeline that use GStreamer-0.10 to GStreamer-1.0

The GstPocketsphinx is not working well. In python, property like lmname, lmctl and dict are not taking in consideration

Moreover there is a big issue when I try to connect the gstpocketsphinx object to a "result" signal.

Please can you provide me an old version (the one working with gtreamer 0.10) I will made all modification to support lmname switch

**Comment by nshmyrev** [comment]
Sorry, Benoit, we are not going to support gstreamer-0.10 anymore. If you have any issues with gstreamer 1.0 you are welcome to describe them in more detail.

**Comment by benoitfragit** [comment]
Yes it is normal. I know in fact everything seems to work porting from 0.10
to 1.0 is not difficult but when I tried to initialise the pipeline Like
this

self.pipe = Gst.parse_launch('alsasrc ! audioconvert ! audioresample !
pocketsphinx name="asr" ! fakesink')

asr = self.pipe.get_by_name("asr")

asr.set_property("lmctl", lmctl) """ this work """
asr.set_property("lmname", lmname) """work too"""
asr.set_property("dict", dict) """ not working load the default english
dict file not the one given in args"""

self.pipe.set_state(Gst.State.PLAYING)

So custom dict loading is no more available

Benoit Franquet
Ingénieur Altran, Ensearque
Le 17 juin 2015 23:15, "Nickolay V. Shmyrev" <notifications@github.com> a
écrit :

**Comment by benoitfragit** [comment]
Sorry I forgot to say that maybe the hmm not loaded too

Benoit Franquet
Ingénieur Altran, Ensearque
Le 17 juin 2015 23:38, "benoit franquet" <benoitfranquet@gmail.com> a
écrit :

**Comment by benoitfragit** [comment]
Hi Nickolay

I see the pocketsphinx object is initialized wjith default args. Make a
set_property does nothing except modifying a ps_config object . Then
setting configured flag launch a ps_reinit with this up to date ps_config.
BUT calling ps_reinit leads to a seg fault. Thats my problem

Benoit Franquet
Ingénieur Altran, Ensearque
Le 17 juin 2015 23:41, "benoit franquet" <benoitfranquet@gmail.com> a
écrit :

**Comment by nshmyrev** [comment]
Please provide an updated code which causes crash

**Comment by benoitfragit** [comment]
Ok i will provide you a n updated pipeline

Benoit Franquet
Ingénieur Altran, Ensearque
Le 18 juin 2015 10:40, "Nickolay V. Shmyrev" <notifications@github.com> a
écrit :

**Comment by benoitfragit** [comment]
Ok here is the pipeline ready to work with Gstreamer 1.0

I've tested it and it "works" :) ! 

Calling the set_property("configured", True) leads to a segfault
Not calling this line make me unable to use my custom dict, hmm and lmname, lmctl file. 

i hope you will find an answer. 

To try this pipeline, you should change all my default files to yours. You should also export the GST_PLUGIN_PATH to the GStreamer 1.0 install.
I hope it will help you ! Tell me if I can help you.

''' Python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, gi, sys

gi.require_version('Gst', '1.0')
from gi.repository import Gst
from gi.repository import GObject

GObject.threads_init()
Gst.init(None)

class Pipeline():
    def __init__(self): 
        """ some file to configure the pipe """               
        self.__dic__   = "/home/benoit/Bureau/Projet/VOXGenerator/test/sphinx/dictionnary.dic"
        self.__hmm__   = "/home/benoit/Bureau/Projet/VOXGenerator/test/sphinx/hmm"
        self.__lmctl__ = "/home/benoit/Bureau/Projet/VOXGenerator/test/lm/lmctl.txt"

        """ very simple pipe """
        self.__pipeline__ = Gst.parse_launch('alsasrc ! audioconvert ! audioresample ! pocketsphinx name=asr ! fakesink')
            
        """ the lmname """ 
        self.__lm__    = "Desktop"
        
        self.__loop__ = GObject.MainLoop()
        self.__previoushyp__ = ""
        
        """ grab the pocketsphinx element 
            without putting asr.set_property("configured", True) all other set_property have no effect on the pocketsphinx
            but calling asr.set_property("configured", True) lead to a segfault 
        """        
        asr = self.__pipeline__.get_by_name('asr')
        asr.set_property('hmm',    self.__hmm__)
        asr.set_property('dict',   self.__dic__)
        asr.set_property('lmctl',  self.__lmctl__)
        asr.set_property("lmname", self.__lm__)
        asr.connect('result', self.__onresult__)
                                
    def __run__(self):
        self.__pipeline__.set_state(Gst.State.PLAYING)
        self.__loop__.run()

    def __pause__(self):
        self.__pipeline__.set_state(Gst.State.PAUSED)       

    def __onresult__(self, asr, text):        
        print "result: " + text

if __name__ == '__main__':
    p = Pipeline()
    p.__run__()
'''

**Comment by benoitfragit** [comment]
I'm trying to use the pipeline below but I still can't make pocketsphinx to work properly.

In order to help you find the problème I've forked pocketsphinx and adding some traces in my  pocketsphinx.c file in the ps_reinit fonction. Then I've launched the pipeline.

I've found that when I call the set_property("configured", True) then a segmentation fault occured in the ps_reinit fonction here (line 307)

``` C
    if ((ps->dict = dict_init(ps->config, ps->acmod->mdef)) == NULL)
        return -1;
```
So I've added traces in teh dict.c file and the segmentation fault comes from this (line 271 -284):

``` C
    fp = NULL;
    n = 0;
    if (dictfile) {
        if ((fp = fopen(dictfile, "r")) == NULL) {
            E_ERROR_SYSTEM("Failed to open dictionary file '%s' for reading", dictfile);
            return NULL;
        }
        for (li = lineiter_start(fp); li; li = lineiter_next(li)) {
            if (0 != strncmp(li->buf, "##", 2)
                && 0 != strncmp(li->buf, ";;", 2))
                n++;
        }
	fseek(fp, 0L, SEEK_SET);
    }
```
There is something very strange here because when we call the first ps_reinit with all default args (ie those define in the MODELDIR path) everything work. So I decided to modify the gst_pocketsphinx_init in order to set my own default args and get the same segmentation fault.

So maybe the problem doesn't come from pocketsphinx but from the french acoustic model/dictionnary that can not be read ! How can I know if those are valid I downloaded them on sourceforge and they work well with an old version of pocketsphinx.

**Comment by benoitfragit** [comment]
Hi Nickolay

In order to be able to use the old the french acoustic model and
dictionnary, I ve forked and reverted to a past version. Now it works. So
maybe the problem cames from those files that can t be parsed by the
current pocketsphinx.

Benoit Franquet
Ingénieur Altran, Ensearque
Le 18 juin 2015 10:56, "benoit franquet" <benoitfranquet@gmail.com> a
écrit :

**Comment by nshmyrev** [comment]
Hi Benoit

Maybe you could share the files so I can understand what is going on there. I’ll look in the coming days and we’ll fix the problem. I’m just a bit busy now.

Thanks

**Comment by benoitfragit** [comment]
Ok i will send you all link to download them tonight

Benoit Franquet
Ingénieur Altran, Ensearque
Le 22 juin 2015 11:57, "Nickolay V. Shmyrev" <notifications@github.com> a
écrit :

**Comment by benoitfragit** [comment]
Hi Nickolay 

Here is the [acoustic langage model](http://downloads.sourceforge.net/project/cmusphinx/Acoustic%20and%20Language%20Models/French%20F0%20Broadcast%20News%20Acoustic%20Model/lium_french_f0.tar.gz
tar zxvf lium_french_f0.tar.gz)

and this the [dictionnary](http://downloads.sourceforge.net/project/cmusphinx/Acoustic%20and%20Language%20Models/French%20Language%20Model/frenchWords62K.dic)

**Comment by benoitfragit** [comment]
I will send you an archive with the pipeline and all the file you need to test.

**Comment by nshmyrev** [comment]
That would be great, thanks a lot!

**Comment by nshmyrev** [comment]
I have reworked this part altogether, it should be way better now. Initialization now delayed to READY state transition.
