### ISSUE TITLE
Seg fault problem

### ISSUE THREAD

**Issue by benoitfragit** [cmusphinx/pocketsphinx#26]
Ps_reinit still lead to a seg fault usig gstpocketsphinx

**Comment by benoitfragit** [comment]
If you tonight I can send a tes pipeline that will show you that the
ps_reinit doesn't do its job. Each time the configured option is modified
then the seg fault appears. I m workin now so I will send you the updated
pipeline tonight

Benoit Franquet
Ingénieur Altran, Ensearque

Closed #26 <https://github.com/cmusphinx/pocketsphinx/issues/26>.

—
Reply to this email directly or view it on GitHub
<https://github.com/cmusphinx/pocketsphinx/issues/26#event-333979625>.

**Comment by nshmyrev** [comment]
Please use issue #25 to discuss this problem, there is no need to discuss same issue in many places
