### ISSUE TITLE
Bring back ps_get_in_speech()

### ISSUE THREAD

**Issue by dhdaines** [cmusphinx/pocketsphinx#262]
Even though it's a bad API (no way to know where the speech started, or how this corresponds to the output alignments) it has the benefit of being dead simple and also really widely used.

The audio buffering done in fe_t is a real mess (for which I claim full responsibility), and this is why the old code had so many problems.  In any case it is preferable to do VAD using MFCC features (before cepstral mean subtraction), at least C0 through C4, and the MFCC buffering in acmod_t is actually done correctly.

It should be feasible to decouple the MFCC buffering and dynamic feature computation from senone computation, and make the buffer big enough to do a simple VAD decision if requested.

As a bonus we could expose the MFCCs and possibly the log-spectrum (or at least the cepstral-smoothed spectrum) to the user, for visualization.

**Comment by dotmain** [comment]
Hi David, 

Curious about how to else speech state if a bad api?! Not familiar with the old implementation.
Thank you.

**Comment by dhdaines** [comment]
Hi! The problem is that "in speech" is not an easy question to answer for an arbitrary microphone and audio environment.  As well, it is not necessarily a question you want to answer for an arbtrarily sized input buffer, which is what the `ps_get_in_speech()` API claims to do.

In general it seems that most applications will do voice activity detection separately from speech recognition (despite the claim to the contrary on the CMUSphinx web page) using a model specifically trained for this, e.g.:

https://github.com/snakers4/silero-vad
https://huggingface.co/pyannote/voice-activity-detection

Or, alternately, voice activity detection will be integrated with speaker diarization (i.e. determining "who spoke when").

**Comment by dhdaines** [comment]
The function is back, but it doesn't do anything particularly useful... should suffice to avoid breaking the API at least.
