### ISSUE TITLE
Andriod build for unreal engine 4.27

### ISSUE THREAD

**Issue by ssshammi** [cmusphinx/pocketsphinx#263]
HI i am able to build exe for windows as the x64 and x84 exist. how to i now add for android what is the extension>

basically i get this error for android 
PackagingResults: Error: assigning field to itself [-Werror,-Wself-assign-field]
PackagingResults: Error: 'sphinxbase/err.h' file not found
PackagingResults: Error: assigning field to itself [-Werror,-Wself-assign-field]
PackagingResults: Error: 'sphinxbase/err.h' file not found
PackagingResults: Error: Unknown Error 

Do i need to build 
.a and .so libraries for android arm8 and arm7va in Third Party plugin ?

**Comment by dhdaines** [comment]
Hi, were you able to build for Android previously?  The build system has changed totally, so it is not surprising.

**Comment by ssshammi** [comment]
Hi i get this error i was able to build for windows.
`UATHelper: Package Plugin Task (Windows):     In file included from D:/Build/andriod/SpeechRecognition/HostProject/Plugins/SpeechRecognition/Source/SpeechRecognition/Private/SpeechRecognition.cpp:3:
UATHelper: Package Plugin Task (Windows):     D:/Build/andriod/SpeechRecognition/HostProject/Plugins/SpeechRecognition/Source/SpeechRecognition/Public/SpeechRecognition.h(81,16): error: assigning field to itself [-Werror,-Wself-assign-field]
UATHelper: Package Plugin Task (Windows):                     this->phrase = phrase;
UATHelper: Package Plugin Task (Windows):                                  ^
UATHelper: Package Plugin Task (Windows): `
@dhdaines 
![image](https://user-images.githubusercontent.com/2300969/178078718-9a618f5a-4ca2-48c5-a726-421a3be710f4.png)

**Comment by dhdaines** [comment]
Hi, I'm sorry, this is not helpful, I know nothing about what you are trying to build or how it is built.  It seems that it's related to some third-party software that uses PocketSphinx, and not the PocketSphinx library itself.

The "assigning field to itself" just looks like some kind of programming error.  As for finding sphinxbase/err.h, well, it should be in the PocketSphixn headers.  I can't help you with your build system which I know nothing about, sorry.

**Comment by ssshammi** [comment]
Oh @dhdaines i managed to resolve the assigning field to itself error.  
the code is using 
![image](https://user-images.githubusercontent.com/2300969/178084741-40954b4a-0c87-46bb-b582-1818244a856b.png)

![image](https://user-images.githubusercontent.com/2300969/178084712-f474855f-a4d5-4630-85f8-fd033219878f.png)

strangely it only fails when i try to build for armv7 
#include <sphinxbase/err.h> Cna you suggest what i need to change. or include in the header.

**Comment by ssshammi** [comment]
It's probably something to do with python make_standalone_toolchain.py --arch armv7 or something

**Comment by dhdaines** [comment]
Hi, I'm really sorry, but make_standalone_toolchain.py is not part of PocketSphinx, I know nothing about it, and I can't help you, sorry.

**Comment by dhdaines** [comment]
Also <sphinxbase/ad.h> has been removed from the current code.  I am open to helping maintainers of 3rd-party packages that use PocketSphinx update their code, but you have given me no information about what you are using and where it came from.

**Comment by ssshammi** [comment]
@dhdaines  oh sorry about this i found the git repo of the project. 
https://github.com/shanecolb/sphinx-ue4/issues/22
I know every little about make file and  [armv7] this is c code. 
![image](https://user-images.githubusercontent.com/2300969/178087084-66b2dbe8-b379-4d46-ad17-8d554f0983f3.png)

I had some hunch that it could be something with a makefile.am or something. 

Thanks again for your help.
