### ISSUE TITLE
Reintegrate pocketsphinx-python code to main source tree

### ISSUE THREAD

**Issue by dhdaines** [cmusphinx/pocketsphinx#269]
It's difficult to understand which version of the Python module is the most functional and least buggy, but a good place to start would be whatever is used by https://github.com/Uberi/speech_recognition - as this, in turn, is used by a variety of other packages.

Honestly I do not understand why anyone would use PocketSphinx for LVCSR, and I hope people won't do it, but I suppose for compatibility reasons we should continue to support this.

**Comment by mrobertscgd** [comment]
Funnily enough, I'm actually using Uberi's speech recognition. Mainly using google's API for when I have a connection and was hoping to use PocketSphinx for offline usage. It'd be really handy to know which version is the most stable for long-term deployment in my project

**Comment by dhdaines** [comment]
Good to know!  The goal is to release PocketSphinx Python packages from the main source branch.  Sadly due to namespace pollution we have to use a new name, which will be "pocketsphinx5".

I will be making a new release candidate quite soon which will get uploaded to PyPI under that name - the APIs from pocketsphinx-python are quite easy to recreate so they should be present there, unless there are some serious problems.

**Comment by mrobertscgd** [comment]
I'll keep an eye on that, it'll be really nice to fix the *mildly infuriating*(even more so because it's not maintained) namespace issue. Let me know if there's anything I can do to help!

**Comment by dhdaines** [comment]
Done since https://github.com/cmusphinx/pocketsphinx/releases/tag/v5.0.0rc3
