### ISSUE TITLE
-cmn in config has no impact

### ISSUE THREAD

**Issue by lenzo-duo** [cmusphinx/pocketsphinx#279]
The -cmn value is not applied if set in config, it just gets the value from the feat.params and doesn't honor the config value when passed in at init.

**Comment by lenzo-duo** [comment]
you can set it in the struct afterwards, but then 'none' doesn't stop -cmninit values from changing

**Comment by dhdaines** [comment]
Oops!  It shouldn't do that...

**Comment by dhdaines** [comment]
Possibly using -cmninit in this way was a bad API, I'll cook something up ASAP (probably this morning)

**Comment by dhdaines** [comment]
Should be fixed by https://github.com/cmusphinx/pocketsphinx/pull/284
