### ISSUE TITLE
New location for cmd_ln_print_values_r(ps->config, err_get_logfp(), ps_args()) can cause exception

### ISSUE THREAD

**Issue by Halle** [cmusphinx/pocketsphinx#28]
Hi all,

I noticed that this has been moved in the post-trie version from the acmod code to pocketsphinx.c:

    cmd_ln_print_values_r(ps->config, err_get_logfp(), ps_args());

Just wanted to give a heads-up that it raises an exception when run here with a ps with:

    err_set_logfp(NULL);

The exception is raised by this line in cmd_ln_print_values_r in cmd_ln.c:

    fprintf(fp, "Current configuration:\n");

I suppose it needs a check for null fp like arg_dump_r has.

**Comment by nshmyrev** [comment]
Thank you for the report!

**Comment by Halle** [comment]
Verified working, thank you!
