### ISSUE TITLE
Save and load config file (format) for decoder

### ISSUE THREAD

**Issue by lenzo-ka** [cmusphinx/pocketsphinx#289]
It would be a nice piece of sugar to be able to load and write configurations from the API (and/or cli args). This would make it easy to re-run things with the same arguments (replicating results and usinga setup on new items), and also open it up to editing the config file to change startup params. Could also potentially contain adapted cmn parameters.

**Comment by lenzo-duo** [comment]
It would be super to have a verbose save that actually includes the values for all parameters, rather than just the ones that are "set" (or differ from defaults).

**Comment by dhdaines** [comment]
Yes, this is a good idea and I will do it.  Possibly just the "argfile" format that is already supported (but not for saving) even though something like YAML would obviously be a lot nicer.

**Comment by dhdaines** [comment]
Implemented in #295 with `ps_config_serialize_json()` - may need a bit of tweaking, currently it is not saving string parameters that are `NULL` but I think it should save them since that might not be the default value
