### ISSUE TITLE
Detect noise level?

### ISSUE THREAD

**Issue by znakeeye** [cmusphinx/pocketsphinx#31]
How can I detect noise level and warn the user if the environment is likely too noisy? I noticed that certain background noise pretty much makes my speech recognition impossible, and I want to detect such conditions.

Maybe something like the getMaxAmplitude API in Android?

**Comment by znakeeye** [comment]
No ideas?

**Comment by nshmyrev** [comment]
This feature is not implemented yet.

**Comment by znakeeye** [comment]
Ok. Is it planned? Would it be hard to implement?

**Comment by benjgorman** [comment]
You should be able to implement it on the android side, as in only run the pocketsphinx activity when the microphone noise level is over a certain threshold.

**Comment by znakeeye** [comment]
But that cannot be done during recognition, can it? Would you need to process the sample buffer in order to get the amplitude in realtime?

**Comment by benjgorman** [comment]
No you should do it before you even start recognition. You can't really account for noise during the recognition, but you can always try and inform the user before you start.

**Comment by ulatekh** [comment]
Can't the average noise level be inferred from the statistics generated in sphinxbase/src/libsphinxbase/fe/fe_noise.c? You may have to read the papers referred to in the comments at the top of fe_noise.c to figure out how to do that.

**Comment by dhdaines** [comment]
Hello, the problem with this is that the type of background noise is very important here.  Stationary noise will simply be removed by cepstral mean normalization, whereas non-stationary noise such as speech will completely destroy recognition accuracy.  Detecting and removing noise is an important part of making ASR work but it is something outside the competencies of the current front-end.  So we will not do it here.
