### ISSUE TITLE
ERROR: Could not build wheels for pocketsphinx, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by DreamedOfIt** [cmusphinx/pocketsphinx#323]
(PY 3.11 DOESNT WORK) ive tried everything by downloading it manually, using git and more (i am on windows), i updated pip(3), and more i also tryed downloading visualstudio with the python enviorment as the error insisted, updating my python, i even updated my laptop but i still cant get it to work. but im not giving up, although i am very frustrated

**Comment by DreamedOfIt** [comment]
i have found the probl

**Comment by DreamedOfIt** [comment]
i have found the problem, (PY 3.11 DOESNT WORK)

**Comment by dhdaines** [comment]
ohhh .... thank you for finding the problem!  I will see if there's something I can do about python 3.11 compatibility (or maybe just build binary wheels for it)

**Comment by tp1415926535** [comment]
Python 3.9.13 but same problem
