### ISSUE TITLE
Rust bindings

### ISSUE THREAD

**Issue by dhdaines** [cmusphinx/pocketsphinx#325]
They exist but should be updated: https://github.com/cmusphinx/pocketsphinx-rs

We can do this after the SoundSwallower ones and make the API compatible: https://github.com/ReadAlongs/SoundSwallower/issues/44

**Comment by mmende** [comment]
I created a new crate with up-to-date rust bindings over here: https://github.com/mmende/pocketsphinx-rs
Basic stuff such as configuration, decoding and endpointing are implemented already, more advanced features are on my list. It is not published yet though.

**Comment by dhdaines** [comment]
Cool! Thanks!
