### ISSUE TITLE
MSVC building

### ISSUE THREAD

**Issue by Molochnik** [cmusphinx/pocketsphinx#327]
I have got a code of both SphinxBase and PocketSphinx from 2020 with .sln and ,vcxproj files. I don't quite remember how I got them, but I dont see them in the present project, also the code files structure changed significantly since then. What should I do to compile it under MSVC now?

**Comment by dhdaines** [comment]
Hello, it now uses [CMake](https://cmake.org/download/).  Recent versions of Visual Studio should be able to support this directly, or if not, you can generate the build files using the CMake GUI or command-line.

Visual Studio Code can also be used, of course.

**Comment by Molochnik** [comment]
Ok thank you!
