### ISSUE TITLE
Phone-align with the most recent merge does not work(or maybe not the same way?)

### ISSUE THREAD

**Issue by BlaChang** [cmusphinx/pocketsphinx#329]
As said in the README:
<img width="829" alt="image" src="https://user-images.githubusercontent.com/109712382/216335638-82991f71-fcdd-4826-8dec-512614781eb7.png">

Now this command returns an empty output, but on previous commits it works.

**Comment by dhdaines** [comment]
Thanks for noticing this! It turns out the test suite was broken :( so it didn't catch the problem.  Fixing it now.
