### ISSUE TITLE
Cannot build both C code and Python module

### ISSUE THREAD

**Issue by flyn-org** [cmusphinx/pocketsphinx#342]
I maintain the pocketsphinx package for Fedora, and I am presently trying to package the recent 5.0.0. release.

I cannot seem to figure out how to build both pocketsphinx's C code and Python module at the same time. It seems you have to run cmake separately for each. Indeed, pocketsphinx's `CMakeLists.txt` file appears to have a conditional that enforces this.

Would it be possible to modify `CMakeLists.txt` to build both components of pocketsphinx with one cmake run?

**Comment by dhdaines** [comment]
Unfortunately no, this is not possible, since it is a completely different CMake configuration - in fact the Python build runs CMake from scikit-build, which adds its own custom modules.

I don't see a good reason to do this, it's possible to simply run both builds from the same script, right?

**Comment by flyn-org** [comment]
I kludged up a solution by moving build directories in between builds and installs. I am not sure if any other Fedora packages do this. If I find one, then I will adopt its approach.
