### ISSUE TITLE
Creating pocketsphinx DLL

### ISSUE THREAD

**Issue by yuvalkry** [cmusphinx/pocketsphinx#367]
Hello,

  The cmake file creates pocketsphinx.lib, what to do in order to create pocketphin.dll?

   Thanks,
       Yuval

**Comment by dhdaines** [comment]
CMake's syntax here leaves a bit to be desired but:
```
cmake -S. -Bbuild -DBUILD_SHARED_LIBS=yes
cmake --build build
```
This should be in the README so I'll leave the issue open until I do that (soon)

**Comment by yuvalkry** [comment]
Thank you!
