### ISSUE TITLE
Adjust the length of quiet that causes the end of an utterance?

### ISSUE THREAD

**Issue by daanzu** [cmusphinx/pocketsphinx#37]
Is there a parameter or other way to adjust the length of quiet that causes the end of an utterance? For instance, I'd like to allow for longer pauses in speech without ending the utterance, so I don't get many very short utterances. Thanks!

**Comment by nshmyrev** [comment]
It is not recommended to include silence in the utterance, it breaks decoding accuracy. For that reason you need to decode utterances separately, not joined together.
