### ISSUE TITLE
User ERROR: en-us does not contain acoustic model definition 'mdef'

### ISSUE THREAD

**Issue by CharlieXuJk** [cmusphinx/pocketsphinx#384]
Hi team, I installed pocketsphinx by `pip install pocketsphinx`. And I am trying to use pocketsphinx in python, But i got error:

> User ERROR: "acmod.c", line 73: Folder 'venv/lib/python3.9/site-packages/pocketsphinx/model/en-us' does not contain acoustic model definition 'mdef'

May I ask what is the correct way to install pocketspinx?

**Comment by dhdaines** [comment]
For historical reasons the acoustic model is in another subdirectory also called `en-us`.  If you look in `venv/lib/python3.9/site-packages/pocketsphinx/model/en-us/en-us` you should see it there.

**Comment by CharlieXuJk** [comment]
Cool thank you!
