### ISSUE TITLE
gstpocketsphinx.c: can't set hmm property when default hmm directory doesn't exist

### ISSUE THREAD

**Issue by thomas536** [cmusphinx/pocketsphinx#39]
I'm trying to specify -hmm via gst properties (I'm using gst1.0), but it's failing because my machine doesn't have a model in the default -hmm value's path.

In gst_pocketsphinx_init, if the directory specified by -hmm (or the default -hmm value) doesn't exist, cmd_ln_parse_r returns NULL [1], which causes the `ps->ps == NULL` check to raise an error.  This is all done before properties have been set.  So I assume the `ps_init` call and NULL check should be done after the properties are set.

[1] `0:00:03.679641618  1635      0x1c10aa0 ERROR           pocketsphinx :0:: ERROR: "acmod.c", line 80: Acoustic model definition is not specified either with -mdef option or with -hmm`

**Comment by nshmyrev** [comment]
Yeah, we just discussed that on forum this week. This whole thing needs update, I'll try to look over weekend.

**Comment by nshmyrev** [comment]
This issue should be fixed now.
