### ISSUE TITLE
ps_get_hyp_final is not available in Python

### ISSUE THREAD

**Issue by VTopoliuk** [cmusphinx/pocketsphinx#40]
**ps_get_hyp** function was ported to Python, but **ps_get_hyp_final** was not. Without this function it's no way to check if hypothesis is reached final state in the grammar.
[pocketsphinx.c:1213](https://github.com/cmusphinx/pocketsphinx/blob/master/src/libpocketsphinx/pocketsphinx.c#L1213)

**Comment by mbait** [comment]
@nshmyrev will correct me if I'm wrong, but as far as I know this function has been deprecated in favor of `ps_get_hyp`.

**Comment by nshmyrev** [comment]
We probably won't support this function in the future
