### ISSUE TITLE
pocketsphinx error

### ISSUE THREAD

**Issue by sudhinsr** [cmusphinx/pocketsphinx#41]
while I try to compile decoder_test.py file

`  File "decoder_test.py", line 39, in <module>
    from pocketsphinx.pocketsphinx import *
ImportError: No module named pocketsphinx`

I have installed pocketsphinx and sphinxbase correctly as mentioned in documentation
`import pocketsphinx` works perfectly 
But then occur Decoder error
`AttributeError: 'module' object has no attribute 'Decoder'`

**Comment by nshmyrev** [comment]
You already asked it in other place

http://stackoverflow.com/questions/34574068/getting-error-on-importing-pocketsphinx
