### ISSUE TITLE
Does the latest acoustic model from cmusphinx work with pocketsphinx

### ISSUE THREAD

**Issue by jainanshul** [cmusphinx/pocketsphinx#42]
There is a new acoustic model available at [US English Generic Acoustic Model](http://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English%20Generic%20Acoustic%20Model/) and am wondering if someone knew if this model works well with pocketsphinx as a replacement of model available in mode/en-Us folder?

**Comment by nshmyrev** [comment]
It works, moreover, it is the same model included in pocketsphinx.
