### ISSUE TITLE
Running from stdin

### ISSUE THREAD

**Issue by mingram8** [cmusphinx/pocketsphinx#43]
I would like to stream audio from another computer to run pocketsphinx on my beefy desktop, right now I have it running on an interval, but it would be nice if I could just run: arecord -D plughw:1,0 -f S16_LE -r 16000 | ssh -C mingram@192.168.86.101 pocketsphinx_continuous

**Comment by mingram8** [comment]
nevermind, looks like I can do -infile /dev/stdin

**Comment by nshmyrev** [comment]
Yup, something like that.
