### ISSUE TITLE
Setting a maximum listening time

### ISSUE THREAD

**Issue by mingram8** [cmusphinx/pocketsphinx#44]
Is there a way to set a timeout, where it stops and computes what was said even though voice is still happening? The TV really messes with it and all of my commands are no more than 4 words. Meaning if I could set a max timeout at like 5 continuous seconds, that would be nice.

**Comment by mbait** [comment]
You can easily do it yourself.

**Comment by mingram8** [comment]
That is what I did.

**Comment by nshmyrev** [comment]
Not sure what the problem is then. Feel free to elaborate.

**Comment by mingram8** [comment]
I wanted a flag to be passed in that would cut off the recognizer to flush the results after a certain amount of time. The TV is at the perfect tone that it won't stop running until the show stops, I am using the library for home automation and all of my commands are about 5 seconds in length, so I didn't need it to wait for long dictation. I was curious if this was already in the library, but instead I added it myself.

**Comment by sdejonckheere** [comment]
Something I noticed in pocketsphinx is that it would recognize speech input from ambient sources such as TV/music/background noises without actually changing the hypothesis. 

My pseudocode looks like:

if hypothesis !changed -> call onResult;

Now my apps works pretty good in noisy environments. Not sure if this is the prefered way.

**Comment by nshmyrev** [comment]
@sdejonckheere , I'm sorry, I don't understand your proposal either. For continuous listening we recommend keyword spotting model.

**Comment by yapro** [comment]
This is a topical issue for me, @mingram8 how you do it?
