### ISSUE TITLE
ps_default_search_args not usable?

### ISSUE THREAD

**Issue by robinp** [cmusphinx/pocketsphinx#49]
Hello,

As it has type `void ps_default_search_args(cmd_ln_t *)`, I would expect the caller should allocate the output struct and pass the pointer to it. But since `cmd_ln_t` is an opaque type to `cmd_ln_s`, and the latter is only defined in `.c` and not in the header, how can a client know its allocation size (based only on the header)?

Not crucial to use that function, but once it's there I wonder about its use.

**Comment by mbait** [comment]
You don't. See
https://github.com/cmusphinx/pocketsphinx/blob/master/test/unit/test_ps_reinit.c#L14
for the reference way of initialization.

On Mon, Apr 18, 2016 at 11:05 AM, Robin Palotai <notifications@github.com>
wrote:

> Hello,
>
> As it has type void ps_default_search_args(cmd_ln_t *), I would expect
> the caller should allocate the output struct and pass the pointer to it.
> But since cmd_ln_t is an opaque type to cmd_ln_s, and the latter is only
> defined in .c and not in the header, how can a client know its allocation
> size (based only on the header)?
>
> Not crucial to use that function, but once it's there I wonder about its
> use.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/cmusphinx/pocketsphinx/issues/49>
>



-- 
Sincerely, Alexander

**Comment by robinp** [comment]
I'm fine with this being closed. But then why is the method in the public header? Sounds like should be migrated to some internal helper.

**Comment by nshmyrev** [comment]
It might be used in software to use default models installed with pocketsphinx, see batch.c or continuous.c or gst plugin code.
