### ISSUE TITLE
ps_seg_frames() returned frame numbers are not precise

### ISSUE THREAD

**Issue by maxrd2** [cmusphinx/pocketsphinx#50]
Using pocketsphinx 5prealpha (2016-02-23) downloaded/built from here: http://downloads.sourceforge.net/cmusphinx/pocketsphinx-5prealpha.tar.gz

When doing speech recognition on longer audio streams the frame numbers returned by ps_seg_frames() are incorrect by ~0.2%.
At the beginning of stream they are ok, but as stream goes onward the error is bigger, so somewhere at 6minutes into the stream the frame numbers are around 1sec too early.

Below is the code snippet... millisecondStartTime becomes more and more incorrect further into the stream.
```c++
	m_psFrameRate = cmd_ln_int32_r(m_psConfig, "-frate");
	int wordIn, wordOut;
	ps_seg_frames(iter, &wordIn, &wordOut);
	double millisecondStartTime = double(wordIn) * 1000. / double(m_psFrameRate);

```

Here is the full source code: https://github.com/maxrd2/subtitlecomposer/blob/master/src/speechplugins/pocketsphinx/pocketsphinxplugin.cpp#L104

**Comment by nshmyrev** [comment]
Yes, there is such problem and it is not quite clear why it happens. We'll need some time to investigate

**Comment by maxrd2** [comment]
Is there some intro doc for new developers or something similar where i could get few hints on where/how audio is processed?
I'm pretty unfamiliar with the codebase and would like to investigate further myself, so anything that could save me some time would be great.

**Comment by nshmyrev** [comment]
Let the source be with you

**Comment by maxrd2** [comment]
haha

**Comment by maxrd2** [comment]
Think this one can be closed. Have found the problem in sphinxbase.

**Comment by nshmyrev** [comment]
Thank you
