### ISSUE TITLE
Patch for Docs:  Additional information about setup of GStreamer plugin

### ISSUE THREAD

**Issue by bidafiwoc** [cmusphinx/pocketsphinx#52]
I've recently been getting up-to-speed on using the GStreamer plugin for PocketSphinx (5prealpha).  As part of getting that to work, I referenced the following handy tutorial:

  http://cmusphinx.sourceforge.net/wiki/gstreamer

It turns out that I had to figure out a few things regarding the PocketSphinx compilation process, in order to make everything work.  I'm submitting this issue, as a type of git 'pull-request', in order to submit some additional documentation to be added to the above wiki-page.  (Normally, if the wiki were under version control, I'd fork, commit, and issue a real pull request, but I see that it's not in github; further, the wiki is read-only, so I couldn't change directly).

Anyway, I'd suggest adding the following extra few paragraphs at the end of the **Overview** section, and right before the start of the **Background Reading** section:

***************************************************

If you instead see something like this:

```
No such element or plugin 'pocketsphinx'
```
or, perhaps:
```
(gst-inspect-1.0:27551): GStreamer-WARNING **: Failed to load plugin 'pocketsphinx': pocketsphinx.so: cannot open shared object file: No such file or directory
Could not load plugin file: Opening module failed: pocketsphinx.so: cannot open shared object file: No such file or directory
```
and all above environmental variables are properly set, it's quite possible that you haven't properly compiled the GStreamer plugin as part of your initial autoconf setup of PocketSphinx.

Some context:  PocketSphinx will automatically build the GStreamer plugin, as part of the normal build process, so long as the appropriate GStreamer 1.0 dev files (header files, etc) are present and identified on your development platform.  PocketSphinx tests for them via the pkg-config infrastructure (which allows libraries to place `.pc` package-configuration files on a system, so that other software has a unified interface to query for library location, version info, compiler/linker flags, etc.).  If these `.pc` files are not identified during execution of the `configure` script (typically called automatically by `autogen.sh`), then their absence will be noted in the script's output log.  However, the script will proceed to configure PocketSphinx without them (the GStreamer plugin, after all, is an *optional* component of PocketSphinx).

In particular, PocketSphinx requires that the following three `.pc` files be available in order to configure the platform to build the GStreamer plugin :
```
gstreamer-1.0.pc
gstreamer-base-1.0.pc
gstreamer-plugins-base-1.0.pc
```
These files can be stored in different locations based on O/S preferences.  To confirm the particular search path that pkg-config uses to find such `.pc` files, you can run:
```
pkg-config --variable pc_path pkg-config
```
Further, assuming you do not compile GStreamer from source, these files are distributed via different packages depending upon your O/S.  (For example, in Debian [Jessie], the first two are provided in the `libgstreamer1.0-dev` package and the last one is provided in the	`libgstreamer-plugins-base1.0-dev` package.)

Once the proper GStreamer dev packages are installed, and you've confirmed that the `.pc` files are in your `pkg-config` path, you can re-configure, re-make, and re-install PocketSphinx.  Now, when you execute `gst-inspect-1.0 pocketsphinx`, you should see that GStreamer can indeed locate the PocketSphinx plugin (as shown in the output above).

***************************************************

Hope this documentation patch proves helpful to others.  Obviously, feel free to modify the above suggested addition to suit developers' preferences (and/or to clarify / correct my understanding).

Thanks for a great ASR system!

**Comment by nshmyrev** [comment]
Thank you for your contribution. I've updated Overview section in gstreamer tutorial according to your notes. Further suggestions are welcome
