### ISSUE TITLE
Carbon Component Manager issue

### ISSUE THREAD

**Issue by ss-pq** [cmusphinx/pocketsphinx#54]
Hi, 

Installed pocket sphinx and base but when running the continuous mode it presents the following:

This application, or a library it uses, is using the deprecated Carbon Component Manager for hosting Audio Units. Support for this will be removed in a future release. Also, this makes the host incompatible with version 3 audio units. Please transition to the API's in AudioComponent.h.

Any solutions for this?

**Comment by nshmyrev** [comment]
This is a bug in openal dependency. Probably you have something like openal-soft replacing openal and that uses deprecated API

To figure out what OpenAL are you using run 

    otool -L /usr/local/bin/pocketsphinx_continuous

and provide the output. Check what version your OpenAL has and why it is out of sync with the system.
