### ISSUE TITLE
Error when installing sphinxbase from sourceforge

### ISSUE THREAD

**Issue by angoodkind** [cmusphinx/pocketsphinx#55]
When sphinxbase is installed from sourceforge, the subsequent installation of pocketsphinx fails.

During the installation of pocketsphinx, when running `make check` it throws the following error:
```
ld: warning: directory not found for option '-L/Users/adamg/te/Polli/ASR/Sphinx/pocketsphinx/../sphinxbase-5prealpha/lib'
Undefined symbols for architecture x86_64:
  "_cmn_live_set", referenced from:
      _main in test_acmod.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [test_acmod] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check-recursive] Error 1
```

Compiling the github version of sphinxbase, though, does not cause this issue.

**Comment by nshmyrev** [comment]
This error means you have old sphinxbase.

**Comment by angoodkind** [comment]
The problem is that the sphinxbase on sourceforge is old. The readme should link to the sphinxbase on github.

**Comment by nshmyrev** [comment]
Then people will complain that pocketsphinx from sourceforge does not work according to readme.

**Comment by angoodkind** [comment]
There seems to be a misunderstanding here. When installing pocketsphinx from github, you also need to use the version of sphinxbase from github. Thus, in the readme on github, the github version of sphinxbase should be linked to.

**Comment by nshmyrev** [comment]
It is not possible to have different readmes for github and for packages.
