### ISSUE TITLE
FATAL: "cmn.c", line 126: Unknown CMN type 'batch'

### ISSUE THREAD

**Issue by erickmiller** [cmusphinx/pocketsphinx#57]
I've followed the install directions, have successfully built and installed latest versions of sphinxbase from sourceforge and pocketsphinx from this repo, and made sure my audio file is 16khz 16bit mono file by resampling it with sox -- but when I attempt to run:

**pocketsphinx_continuous -infile resampled_audio.wav** 

I get the following output, which ends in a FATAL error **FATAL: "cmn.c", line 126: Unknown CMN type 'batch'** (see below)

Please help!  Thanks

INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/share/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+00
-allphone				
-allphone_ci		no		no
-alpha			0.97		9.700000e-01
-ascale			20.0		2.000000e+01
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-48
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+00
-ceplen			13		13
-cmn			current		batch
-cmninit		8.0		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen		no		no
-debug					0
-dict					/usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				
-fillprob		1e-8		1.000000e-08
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-64
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+00
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-29
-fwdtree		yes		yes
-hmm					/usr/local/share/pocketsphinx/model/en-us/en-us
-input_endian		little		little
-jsgf					
-keyphrase				
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-01
-kws_threshold		1		1.000000e+00
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					/usr/local/share/pocketsphinx/model/en-us/en-us.lm.bin
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+00
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+02
-lpbeam			1e-40		1.000000e-40
-lponlybeam		7e-29		7.000000e-29
-lw			6.5		6.500000e+00
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					
-mean					
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-07
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+00
-pbeam			1e-48		1.000000e-48
-pip			1.0		1.000000e+00
-pl_beam		1e-10		1.000000e-10
-pl_pbeam		1e-10		1.000000e-10
-pl_pip			1.0		1.000000e+00
-pl_weight		3.0		3.000000e+00
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+04
-seed			-1		-1
-sendump				
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-03
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					
-tmatfloor		0.0001		1.000000e-04
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+03
-uw			1.0		1.000000e+00
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		2.0		2.000000e+00
-var					
-varfloor		0.0001		1.000000e-04
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-29
-wip			0.65		6.500000e-01
-wlen			0.025625	2.562500e-02

**FATAL: "cmn.c", line 126: Unknown CMN type 'batch'**

**Comment by nshmyrev** [comment]
You need to reinstall sphinxbase from github too.

**Comment by ugochirico** [comment]
I've just downloaded from github the latest versions of sphinxbase and pocketsphinx but running pocketsphinx_continuos I got:- "FATAL: "cmn.c", line 126: Unknown CMN type 'live''
This means that the latest versions on github doesn't work. 
How can I solve it?

**Comment by ss-pq** [comment]
Have you tried current?

**Comment by ugochirico** [comment]
Yes. Right now,

**Comment by ss-pq** [comment]
@ugochirico 
Is it working?

**Comment by ugochirico** [comment]
no. It doesn't work

**Comment by ss-pq** [comment]
These are the possible settings:
 [ 13] {
            :name => "cmn",
            :type => :string,
         :default => "current",
        :required => false,
           :value => "current",
            :info => "Cepstral mean normalization scheme ('current', 'prior', or 'none')"
    }


Make sure to have a recent build.

**Comment by ugochirico** [comment]
ok. It works now. I got the pocketsphinx package from sourcefourge instead of github. 
Sorry to bother you.
Many thanks!

**Comment by gatlin** [comment]
I installed both pocketsphinx (commit c178c8dc19486) and sphinxbase (commit a74a11df3a021e9a2) from the cmusphinx github repositories, compiling them both with the prefix `$HOME/sphinx/build`. Both compiled successfully, and the first of [the example code listings][examples] compiled and ran without incident. 

However, the second one ("decoding a file stream") compiled and then failed at runtime with output similar to what has been reported above. 

The notable part is at the end: `FATAL: "cmn.c", line 126: Unknown CMN type 'batch'`. Here is the full output:

```
[gcj@exodus sphinx]$ ./hello_ps 
INFO: pocketsphinx.c(145): Parsed model-specific feature parameters from /home/gcj/sphinx/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+00
-allphone				
-allphone_ci		no		no
-alpha			0.97		9.700000e-01
-ascale			20.0		2.000000e+01
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-48
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+00
-ceplen			13		13
-cmn			current		batch
-cmninit		8.0		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen		no		no
-debug					0
-dict					/home/gcj/sphinx/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/noisedict
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/feat.params
-fillprob		1e-8		1.000000e-08
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-64
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+00
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-29
-fwdtree		yes		yes
-hmm					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us
-input_endian		little		little
-jsgf					
-keyphrase				
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-01
-kws_threshold		1		1.000000e+00
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us.lm.bin
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+00
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+02
-lpbeam			1e-40		1.000000e-40
-lponlybeam		7e-29		7.000000e-29
-lw			6.5		6.500000e+00
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/mdef
-mean					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/means
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-07
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+00
-pbeam			1e-48		1.000000e-48
-pip			1.0		1.000000e+00
-pl_beam		1e-10		1.000000e-10
-pl_pbeam		1e-10		1.000000e-10
-pl_pip			1.0		1.000000e+00
-pl_weight		3.0		3.000000e+00
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+04
-seed			-1		-1
-sendump				/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/sendump
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-03
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/transition_matrices
-tmatfloor		0.0001		1.000000e-04
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+03
-uw			1.0		1.000000e+00
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		2.0		2.000000e+00
-var					/home/gcj/sphinx/pocketsphinx/model/en-us/en-us/variances
-varfloor		0.0001		1.000000e-04
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-29
-wip			0.65		6.500000e-01
-wlen			0.025625	2.562500e-02

FATAL: "cmn.c", line 126: Unknown CMN type 'batch'
```

[examples]: https://cmusphinx.github.io/wiki/tutorialpocketsphinx/

**Comment by gatlin** [comment]
@nshmyrev The output I get for that is

    [gcj@exodus ~]$ ldd `which pocketsphinx_continuous`
    ldd: missing file arguments
    Try `ldd --help' for more information.
    [gcj@exodus ~]$ which pocketsphinx_continuous

**Comment by joe95it** [comment]
but I had the idea to replace the default file (found on the sphinxbase files) feat.params with that of the Italian acoustic model that I downloaded and then I ran the same command line, the result is this:
----------------------------------------------------------------------------------------------------------------
`root@raspberrypi:/home/pi# pocketsphinx_continuous -hmm /home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000 -lm /home/pi/jasper/cmusphinx-it-5.2/etc/voxforge_it_sphinx.lm -dict /home/pi/jasper/it/it.dic -infile test.wav
INFO: cmd_ln.c(691): Parsing command line:
pocketsphinx_continuous \
	-hmm /home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000 \
	-lm /home/pi/jasper/cmusphinx-it-5.2/etc/voxforge_it_sphinx.lm \
	-dict /home/pi/jasper/it/it.dic \
	-infile test.wav 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-adcdev				
-agc		none		none
-agcthresh	2.0		2.000000e+00
-alpha		0.97		9.700000e-01
-argfile			
-ascale		20.0		2.000000e+01
-aw		1		1
-backtrace	no		no
-beam		1e-48		1.000000e-48
-bestpath	yes		yes
-bestpathlw	9.5		9.500000e+00
-bghist		no		no
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		8.0
-compallsen	no		no
-debug				0
-dict				/home/pi/jasper/it/it.dic
-dictcase	no		no
-dither		no		no
-doublebw	no		no
-ds		1		1
-fdict				
-feat		1s_c_d_dd	1s_c_d_dd
-featparams			
-fillprob	1e-8		1.000000e-08
-frate		100		100
-fsg				
-fsgusealtpron	yes		yes
-fsgusefiller	yes		yes
-fwdflat	yes		yes
-fwdflatbeam	1e-64		1.000000e-64
-fwdflatefwid	4		4
-fwdflatlw	8.5		8.500000e+00
-fwdflatsfwin	25		25
-fwdflatwbeam	7e-29		7.000000e-29
-fwdtree	yes		yes
-hmm				/home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000
-infile				test.wav
-input_endian	little		little
-jsgf				
-kdmaxbbi	-1		-1
-kdmaxdepth	0		0
-kdtree				
-latsize	5000		5000
-lda				
-ldadim		0		0
-lextreedump	0		0
-lifter		0		0
-lm				/home/pi/jasper/cmusphinx-it-5.2/etc/voxforge_it_sphinx.lm
-lmctl				
-lmname		default		default
-logbase	1.0001		1.000100e+00
-logfn				
-logspec	no		no
-lowerf		133.33334	1.333333e+02
-lpbeam		1e-40		1.000000e-40
-lponlybeam	7e-29		7.000000e-29
-lw		6.5		6.500000e+00
-maxhmmpf	-1		-1
-maxnewoov	20		20
-maxwpf		-1		-1
-mdef				
-mean				
-mfclogdir			
-min_endfr	0		0
-mixw				
-mixwfloor	0.0000001	1.000000e-07
-mllr				
-mmap		yes		yes
-ncep		13		13
-nfft		512		512
-nfilt		40		40
-nwpen		1.0		1.000000e+00
-pbeam		1e-48		1.000000e-48
-pip		1.0		1.000000e+00
-pl_beam	1e-10		1.000000e-10
-pl_pbeam	1e-5		1.000000e-05
-pl_window	0		0
-rawlogdir			
-remove_dc	no		no
-round_filters	yes		yes
-samprate	16000		1.600000e+04
-seed		-1		-1
-sendump			
-senlogdir			
-senmgau			
-silprob	0.005		5.000000e-03
-smoothspec	no		no
-svspec				
-time		no		no
-tmat				
-tmatfloor	0.0001		1.000000e-04
-topn		4		4
-topn_beam	0		0
-toprule			
-transform	legacy		legacy
-unit_area	yes		yes
-upperf		6855.4976	6.855498e+03
-usewdphones	no		no
-uw		1.0		1.000000e+00
-var				
-varfloor	0.0001		1.000000e-04
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wbeam		7e-29		7.000000e-29
-wip		0.65		6.500000e-01
-wlen		0.025625	2.562500e-02

INFO: cmd_ln.c(691): Parsing command line:
\
	-nfilt 20 \
	-lowerf 1 \
	-upperf 4000 \
	-wlen 0.025 \
	-transform dct \
	-round_filters no \
	-remove_dc yes \
	-svspec 0-12/13-25/26-38 \
	-feat 1s_c_d_dd \
	-agc none \
	-cmn current \
	-cmninit 56,-3,1 \
	-varnorm no 

Current configuration:
[NAME]		[DEFLT]		[VALUE]
-agc		none		none
-agcthresh	2.0		2.000000e+00
-alpha		0.97		9.700000e-01
-ceplen		13		13
-cmn		current		current
-cmninit	8.0		56,-3,1
-dither		no		no
-doublebw	no		no
-feat		1s_c_d_dd	1s_c_d_dd
-frate		100		100
-input_endian	little		little
-lda				/home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000/feature_transform
-ldadim		0		0
-lifter		0		0
-logspec	no		no
-lowerf		133.33334	1.000000e+00
-ncep		13		13
-nfft		512		512
-nfilt		40		20
-remove_dc	no		yes
-round_filters	yes		no
-samprate	16000		1.600000e+04
-seed		-1		-1
-smoothspec	no		no
-svspec				0-12/13-25/26-38
-transform	legacy		dct
-unit_area	yes		yes
-upperf		6855.4976	4.000000e+03
-varnorm	no		no
-verbose	no		no
-warp_params			
-warp_type	inverse_linear	inverse_linear
-wlen		0.025625	2.500000e-02

INFO: acmod.c(246): Parsed model-specific feature parameters from /home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000/feat.params
INFO: feat.c(713): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='current', VARNORM='no', AGC='none'
INFO: cmn.c(142): mean[0]= 12.00, mean[1..12]= 0.0
INFO: acmod.c(157): Reading linear feature transformation from /home/pi/jasper/cmusphinx-it-5.2/model_parameters/voxforge_it_sphinx.cd_cont_2000/feature_transform
INFO: acmod.c(167): Using subvector specification 0-12/13-25/26-38
ERROR: "feat.c", line 310: Total dimensionality of subvector specification 39 > feature dimensionality 32
`

**Comment by nshmyrev** [comment]
@joe95it your problems are not related to this issue. And github is not the right place to discuss them, you can open a new thread on forum.

**Comment by nshmyrev** [comment]
@gatlin do you have pocketsphinx installed at all? I also recommend you to refrain from hijacking the irrelevant thread and open new discussion on forum.

**Comment by mvrk33** [comment]
it worked for me on raspberry pi 3 b+
cd ~/
export LD_LIBRARY_PATH=/usr/local/lib
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by gatlin** [comment]
@nshmyrev My apologies, I thought it would be more annoying to open a new thread for the same issue.
