### ISSUE TITLE
ERROR: "ngram_model_trie.c", line 447: Dump file /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm not found

### ISSUE THREAD

**Issue by erickmiller** [cmusphinx/pocketsphinx#58]
I've successfully compiled and installed the newest sphinxbase and pocketsphinx from github.
I ran pocketsphinx_continuous -infile resampled.wav

It generated text from my audio and this was very cool!!  It works!  :)

But the accuracy of the results was below expectations. 

I noticed that the model included with pocketsphinx is a pruned version - meaning words are missing?  So, in an attempt to improve accuracy, I found and tried to install the bigger un-pruned version of the latest language model en-70k-0.2.lm.gz (594.2MB uncompressed) which I found here:

https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/US%20English/

And then tried calling pocketsphinx with the new language model:

pocketsphinx_continuous -infile resampled.wav -lm /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm

Unfortunately this did not work.  

Do I need the corresponding -dict and feat.params / -hmm files for the full language model?  If so, where do I download these from (I wasn't finding them anywhere when I searched)?

I also already tried using the newer cmudict.dict found here:
https://github.com/cmusphinx/cmudict

But that didn't work, and the phones did not match either, but there is a corresponding .phones file included... but not sure how to configure the language model, dict, phones and other files so that they are all in sync?  And how to generate the hmm files?   

UPDATE: I just found this webpage:   http://cmusphinx.sourceforge.net/wiki/tutorialadapt  
But it is unclear if these are the correct steps for me to take?  Do I need to install sphinxtrain or shouldn't there be all the pre-trained data and dictionaries / phoneme files needed to go along with the language model distributed as a single package? 

What can I do to quickly fix this?  I'm hoping to not have to run training in order to test the bigger, more robust language model and dictionary / phonemes...  Below is my output and error messages.  

Please help, thanks! 

INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /usr/local/share/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+00
-allphone				
-allphone_ci		no		no
-alpha			0.97		9.700000e-01
-ascale			20.0		2.000000e+01
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-48
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+00
-ceplen			13		13
-cmn			current		batch
-cmninit		8.0		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen		no		no
-debug					0
-dict					/usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				
-fillprob		1e-8		1.000000e-08
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-64
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+00
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-29
-fwdtree		yes		yes
-hmm					/usr/local/share/pocketsphinx/model/en-us/en-us
-input_endian		little		little
-jsgf					
-keyphrase				
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-01
-kws_threshold		1		1.000000e+00
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					/usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+00
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+02
-lpbeam			1e-40		1.000000e-40
-lponlybeam		7e-29		7.000000e-29
-lw			6.5		6.500000e+00
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					
-mean					
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-07
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+00
-pbeam			1e-48		1.000000e-48
-pip			1.0		1.000000e+00
-pl_beam		1e-10		1.000000e-10
-pl_pbeam		1e-10		1.000000e-10
-pl_pip			1.0		1.000000e+00
-pl_weight		3.0		3.000000e+00
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+04
-seed			-1		-1
-sendump				
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-03
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					
-tmatfloor		0.0001		1.000000e-04
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+03
-uw			1.0		1.000000e+00
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		2.0		2.000000e+00
-var					
-varfloor		0.0001		1.000000e-04
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-29
-wip			0.65		6.500000e-01
-wlen			0.025625	2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='batch', VARNORM='no', AGC='none'
INFO: acmod.c(166): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /usr/local/share/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /usr/local/share/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(117): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /usr/local/share/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /usr/local/share/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 32 bytes (4338 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /usr/local/share/pocketsphinx/model/en-us/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /usr/local/share/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(354): Trying to read LM in trie binary format
ERROR: "ngram_model_trie.c", line 356: File /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm not found
INFO: ngram_model_trie.c(177): Trying to read LM in arpa format
ERROR: "ngram_model_trie.c", line 179: File /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm not found
INFO: ngram_model_trie.c(445): Trying to read LM in dmp format
ERROR: "ngram_model_trie.c", line 447: Dump file /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm not found

**Comment by nshmyrev** [comment]
> So, in an attempt to improve accuracy, I found and tried to install the bigger un-pruned version of the latest language model en-70k-0.2.lm.gz

It is not possible to use big model in pocketsphinx currently

> ERROR: "ngram_model_trie.c", line 356: File /usr/local/share/pocketsphinx/model/en-us/en-70k-0.2.lm not found

This error means file is not present in the location you specified, you need to provide the correct path to the language model file

> What can I do to quickly fix this?

It is not possible to quickly fix accuracy problems, otherwise we'd do that ourselves. In order to get advice on the accuracy you need to provide the test dataset as described here:

http://cmusphinx.sourceforge.net/wiki/tutorialtuning
