### ISSUE TITLE
Example in lm_test.py failing

### ISSUE THREAD

**Issue by emergedev** [cmusphinx/pocketsphinx#59]
https://github.com/cmusphinx/pocketsphinx/blob/master/swig/python/test/lm_test.py

When attempting to run the `lm.prob()` method from the above test script, I'm seeing:

`lm.prob(['you'])`

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "sphinxbase/sphinxbase.py", line 326, in prob
    return _sphinxbase.NGramModel_prob(self, *args)
TypeError: NGramModel_prob() takes exactly 3 arguments (2 given)
```

I built the `decoder` and then created the `lm` with:

`lm = NGramModel(config, decoder.get_logmath(), '/path/to/lm.lm')`

**Comment by nshmyrev** [comment]
I've just pushed an update to sphinxbase to fix this issue. Update sphinxbase, recompile both sphinxbase and pocketsphinx and it should work.
