### ISSUE TITLE
Results are different with and without ps_init

### ISSUE THREAD

**Issue by youwei112233** [cmusphinx/pocketsphinx#60]
Hi Sir,
     I modified the application  of pocketsphinx_continous on Windows to support reading and recognize multiple WAV files  one by one in a directory. There are two cases: one is to call ps_init() each time before processing each input WAV file and the other is only  call ps_init()  once for all these inputs. I found the results are different in these two cases. I don't understand why?
    Look forward to your feedback on this.

**Comment by nshmyrev** [comment]
There are parameters like noise cancellation params or cmn which are reused if you don't reinit recognizer.

**Comment by youwei112233** [comment]
But I don't modify these parameters in these two cases. My understanding is that these parameters also keep unchanged in either case, right? If so, why will it affect the result?

**Comment by nshmyrev** [comment]
If you reinit ps parameters change.

**Comment by youwei112233** [comment]
Thanks for your feedback. But what's the better option for higher recognition rate? Do initialization each time or only once? Can you give us a suggestion?

**Comment by nshmyrev** [comment]
Depends of the audio you want to process, if the audio is sort of the same type (same noise level, same loudness, same channel), you should proceed without initialization. If audios are very differetn (some have higher noise level than others, different microphones), its probably better to reinit every time.

**Comment by youwei112233** [comment]
Thanks  nshmyrev for your rapid and useful feedbacks on my confusions.
