### ISSUE TITLE
A question about Language Model

### ISSUE THREAD

**Issue by youwei112233** [cmusphinx/pocketsphinx#61]
Hi Sir, 
       I encountered a problem about Language Model. Previously I always used online tools to generate the language mode (http://www.speech.cs.cmu.edu/tools/lmtool-new.html). Recently I tried to use the  toolkit of cmuclmtk-0.7 . I download it and compiled it successfully and it can also generate LM (ARPA). The command and parameters I used  as following:
      
**text2wfreq < 2.txt > 2.wfreq
wfreq2vocab < 2.wfreq > 2.vocab
text2idngram -vocab 2.vocab -idngram 2.idngram < 2.txt
idngram2lm -idngram 2.idngram -vocab 2.vocab -arpa 2.arpa -witten_bell -vocab_type 0 -context 2.ccs**

But I found there are many difference between the file of LM generated in these two ways:
(1) The File Size is different.      Online generation is much less than that of cmuclmtk for the same TXT input.  I went through the two files and found that there are extra lines in cmuclmtk output, which look like "-4.1420 \</s\> \<s\> XXXXXXX " or "-0.3010 XXXXXXX\</s\> \<s\> ". \</s\> and \<s\> are put together.

(2)The data or number is different. For example, the first word in section 1-grams of CMUCLMTK is "-3.8410 xxxxxxx -0.3010"   while the output of online is " -4.6192 xxxxxx -0.2218 "

(3) The recognition result is different.  Using these two LMs and keep all others unchanged, the result are different.

 I wonder if there is something wrong with my usage. If not, why are there so big different? which one is better?

**Comment by nshmyrev** [comment]
Server used absolute discount, you can reproduce server results with [quick_lm.pl script](http://www.speech.cs.cmu.edu/tools/download/quick_lm.pl).

You used witten_bell discount in cmuclmtk, it is expected to work for very large data sets and might give you different results. For short data sets quick_lm.pl is better. You can also use absolute discount in cmuclmtk to get good results on small database.
