### ISSUE TITLE
What are the reasons for returning a null hypothesis?

### ISSUE THREAD

**Issue by EdwardBX** [cmusphinx/pocketsphinx#63]
When I test the system with a large number of wav files, I found some results are null hypotheses. But the wav files are all sound clear. Why this happens? 
Do you have some advises to help me  getting rid of these null hypotheses. Thanks.

**Comment by nshmyrev** [comment]
You need to provide more details on what exactly do you run and what do you see to get help on this issue.

**Comment by EdwardBX** [comment]
I want to use the pocketsphinx for Chinese recognition. I am using a AcousticModel named tdt_sc_8k. My wav files contain the sound of word pronunciation.  My brief function call routine as blow:

`
rawfd=GetFirstFileHandle();
while(rawfd) {
	ps=ps_init(config);
	ps_start_utt(ps);
	while ((k = fread(adbuf, sizeof(int16), 2048, rawfd)) > 0) 
		ps_process_raw(ps, adbuf_vol, k, FALSE, FALSE);		
		
	ps_end_utt(ps);
		
	for (n = 1, nbest = ps_nbest(ps); nbest && n < 10; nbest = ps_nbest_next(nbest), n++) 
        // to get the best 10 results if there are engough
		hyp = ps_nbest_hyp(nbest, &score);
					
	ps_free(ps);
	fclose(rawfd);
	rawfd=NextFileHand();
}
`
For some files, it returned NULL even in the first calling of ps_nbest_hyp(). That means it only return null hypotheses.
Can you explain the reason why this happens?

**Comment by nshmyrev** [comment]
You need to share an example of the file

**Comment by EdwardBX** [comment]
[阿波罗.zip](https://github.com/cmusphinx/pocketsphinx/files/504753/default.zip)

This file always returns a null hypothesis. But my dic and lm file are all correct, I think. 
Here are my dic and lm files. 
[dic&dmp.zip](https://github.com/cmusphinx/pocketsphinx/files/504755/dic.dmp.zip)


Are there some tips and tricks that I missed?

**Comment by nshmyrev** [comment]
Well, it's just an accuracy problem. There are few issues here:

- our current Chinese models are not hugely accurate, they are trained on rather limited set of data. You can try [bigger model](https://sourceforge.net/projects/cmusphinx/files/Acoustic%20and%20Language%20Models/Mandarin/) instead, but it's not going to make a huge difference
- your audio is pretty short, you need batch processing for higher accuracy. You need to process whole audio at once with `ps_process_raw` with last argument `full_utt = TRUE`. See [discussion](https://sourceforge.net/p/cmusphinx/discussion/help/thread/51e2979b/)  too.
- your audio has echo, most likely you use laptop microphone in a room. Those are pretty bad and accuracy for them will be low. You need to use better microphone or develop special models to handle echo.

**Comment by EdwardBX** [comment]
Thanks for your help! When I process whole audio at once, it did work! In this way I improve the accuracy highly.
I went through the codes in sphinxBase and found that each time it processed 400 frames as a unit for the input raw data, which is much less than 2048 bytes. So I wonder why the recognize rate is so much different bewteen once reading mode and multi-reading mode(2048 bytes for each time).

**Comment by nshmyrev** [comment]
Details are explained in discussion linked above
