### ISSUE TITLE
Pocketsphinx not detecting speech when paired to bluetooth headset

### ISSUE THREAD

**Issue by ukmarn** [cmusphinx/pocketsphinx#65]
We are using your framework for a long time (Openears) and a month ago we converted it to Swift3 syntax. Everything works great but we noticed when iPhone is connected via bluetooth in car or to any bluetooth headset, speech is not detected. Microphone switches to bluetooth device and doesn't get recognised. Anyone else having this issues?

**Comment by nshmyrev** [comment]
This is a wrong place to ask questions about openears, you can ask on forum http://www.politepix.com/forums/forum/openearsforum/
