### ISSUE TITLE
FATAL: "cmn.c", line 126: Unknown CMN type 'live'

### ISSUE THREAD

**Issue by umrashrf** [cmusphinx/pocketsphinx#67]
`pocketsphinx_continuous -infile audio.wav`

**Comment by nshmyrev** [comment]
Update sphinxbase

**Comment by umrashrf** [comment]
Which version of sphinxbase it needs?

I treid several and none of it worked.

For example, I tried https://github.com/cmusphinx/sphinxbase and https://sourceforge.net/projects/cmusphinx/files/sphinxbase/5prealpha/

**Comment by nshmyrev** [comment]
https://github.com/cmusphinx/sphinxbase

**Comment by umrashrf** [comment]
Same error with that one too

**Comment by nshmyrev** [comment]
Most likely you have older sphinxbase installed in your system, you need to remove it first.

**Comment by chrisbward** [comment]
I'm also having the same issue from a clean install - Ubuntu 16.04

**Comment by chrisbward** [comment]
I was able to resolve this by finding this SO post;
http://stackoverflow.com/questions/4743233/is-usr-local-lib-searched-for-shared-libraries

looks like I hadn't updated the LD path variable, and was able to verify pocketsphinx working with;

LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib pocketsphinx_continuous -inmic yes

**Comment by mvrk33** [comment]
it worked for me on raspberry pi 3 b+
cd ~/
export LD_LIBRARY_PATH=/usr/local/lib
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

**Comment by SBlincov** [comment]
> it worked for me on raspberry pi 3 b+
> cd ~/
> export LD_LIBRARY_PATH=/usr/local/lib
> export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

Thank you so much :)
