### ISSUE TITLE
Pocketsphinx server

### ISSUE THREAD

**Issue by cogmeta** [cmusphinx/pocketsphinx#69]
It is possible to run pocketsphinx as a server and communicate through socket?

**Comment by nshmyrev** [comment]
No, you have to implement it yourself.

**Comment by cogmeta** [comment]
Ok. We have started a c http server for this. I think the flow for each request handler would be as follows:

static ps_decoder_t *ps;
ps_start_utt(ps);
while(data) {
  ps_process_raw(ps, adbuf, k, FALSE, FALSE);
}
ps_end_utt(ps);
ps_get_hyp(ps, NULL );

Are these ps_* functions thread safe?

**Comment by nshmyrev** [comment]
No
