### ISSUE TITLE
ImportError: No module named _ad

### ISSUE THREAD

**Issue by ankurgulati** [cmusphinx/pocketsphinx#70]
Hi,
I am facing a error while importing please help I am using the following command in python 2.7
`from sphinxbase import *`

And following is the error
> ImportError: No module named _ad

I downloaded pocketsphinx using pip install

**Comment by ankurgulati** [comment]
Can you please help me on this one or direct me somewhere ?

**Comment by nshmyrev** [comment]
The module you have trouble with is discussed here: https://github.com/bambocher/pocketsphinx-python

**Comment by nshmyrev** [comment]
Tracked at https://github.com/bambocher/pocketsphinx-python/issues/19
