### ISSUE TITLE
go forward demo get "Recognized: if as it and and and and" result?

### ISSUE THREAD

**Issue by tom8382** [cmusphinx/pocketsphinx#74]
Hi,
   using the latest source code of pocketsphinx, and run the goforward.raw by hello_ps demo. i only get a bad result "if as it and and and and"...., can any one help me??

exbot@wzhl:/home/exbot/sdcard> ./hello_ps                                                                                                17-02-18 15:19
INFO: pocketsphinx.c(152): Parsed model-specific feature parameters from /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/feat.params
Current configuration:
[NAME]			[DEFLT]		[VALUE]
-agc			none		none
-agcthresh		2.0		2.000000e+00
-allphone				
-allphone_ci		yes		yes
-alpha			0.97		9.700000e-01
-ascale			20.0		2.000000e+01
-aw			1		1
-backtrace		no		no
-beam			1e-48		1.000000e-48
-bestpath		yes		yes
-bestpathlw		9.5		9.500000e+00
-ceplen			13		13
-cmn			live		live
-cmninit		40,3,-1		41.00,-5.29,-0.12,5.09,2.48,-4.07,-1.37,-1.78,-5.08,-2.05,-6.45,-1.42,1.17
-compallsen		no		no
-debug					0
-dict					/home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/cmudict-en-us.dict
-dictcase		no		no
-dither			no		no
-doublebw		no		no
-ds			1		1
-fdict					
-feat			1s_c_d_dd	1s_c_d_dd
-featparams				
-fillprob		1e-8		1.000000e-08
-frate			100		100
-fsg					
-fsgusealtpron		yes		yes
-fsgusefiller		yes		yes
-fwdflat		yes		yes
-fwdflatbeam		1e-64		1.000000e-64
-fwdflatefwid		4		4
-fwdflatlw		8.5		8.500000e+00
-fwdflatsfwin		25		25
-fwdflatwbeam		7e-29		7.000000e-29
-fwdtree		yes		yes
-hmm					/home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us
-input_endian		little		little
-jsgf					
-keyphrase				
-kws					
-kws_delay		10		10
-kws_plp		1e-1		1.000000e-01
-kws_threshold		1e-30		1.000000e-30
-latsize		5000		5000
-lda					
-ldadim			0		0
-lifter			0		22
-lm					/home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us.lm.bin
-lmctl					
-lmname					
-logbase		1.0001		1.000100e+00
-logfn					
-logspec		no		no
-lowerf			133.33334	1.300000e+02
-lpbeam			1e-40		1.000000e-40
-lponlybeam		7e-29		7.000000e-29
-lw			6.5		6.500000e+00
-maxhmmpf		30000		30000
-maxwpf			-1		-1
-mdef					
-mean					
-mfclogdir				
-min_endfr		0		0
-mixw					
-mixwfloor		0.0000001	1.000000e-07
-mllr					
-mmap			yes		yes
-ncep			13		13
-nfft			512		512
-nfilt			40		25
-nwpen			1.0		1.000000e+00
-pbeam			1e-48		1.000000e-48
-pip			1.0		1.000000e+00
-pl_beam		1e-10		1.000000e-10
-pl_pbeam		1e-10		1.000000e-10
-pl_pip			1.0		1.000000e+00
-pl_weight		3.0		3.000000e+00
-pl_window		5		5
-rawlogdir				
-remove_dc		no		no
-remove_noise		yes		yes
-remove_silence		yes		yes
-round_filters		yes		yes
-samprate		16000		1.600000e+04
-seed			-1		-1
-sendump				
-senlogdir				
-senmgau				
-silprob		0.005		5.000000e-03
-smoothspec		no		no
-svspec					0-12/13-25/26-38
-tmat					
-tmatfloor		0.0001		1.000000e-04
-topn			4		4
-topn_beam		0		0
-toprule				
-transform		legacy		dct
-unit_area		yes		yes
-upperf			6855.4976	6.800000e+03
-uw			1.0		1.000000e+00
-vad_postspeech		50		50
-vad_prespeech		20		20
-vad_startspeech	10		10
-vad_threshold		3.0		3.000000e+00
-var					
-varfloor		0.0001		1.000000e-04
-varnorm		no		no
-verbose		no		no
-warp_params				
-warp_type		inverse_linear	inverse_linear
-wbeam			7e-29		7.000000e-29
-wip			0.65		6.500000e-01
-wlen			0.025625	2.562500e-02

INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='live', VARNORM='no', AGC='none'
INFO: acmod.c(162): Using subvector specification 0-12/13-25/26-38
INFO: mdef.c(518): Reading model definition: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/mdef
INFO: mdef.c(531): Found byte-order mark BMDF, assuming this is a binary mdef file
INFO: bin_mdef.c(336): Reading binary model definition: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/mdef
INFO: bin_mdef.c(516): 42 CI-phone, 137053 CD-phone, 3 emitstate/phone, 126 CI-sen, 5126 Sen, 29324 Sen-Seq
INFO: tmat.c(149): Reading HMM transition probability matrices: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/transition_matrices
INFO: acmod.c(113): Attempting to use PTM computation module
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/means
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(127): Reading mixture gaussian parameter: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/variances
INFO: ms_gauden.c(242): 42 codebook, 3 feature, size: 
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(244):  128x13
INFO: ms_gauden.c(304): 222 variance values floored
INFO: ptm_mgau.c(476): Loading senones from dump file /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/sendump
INFO: ptm_mgau.c(500): BEGIN FILE FORMAT DESCRIPTION
INFO: ptm_mgau.c(563): Rows: 128, Columns: 5126
INFO: ptm_mgau.c(595): Using memory-mapped I/O for senones
INFO: ptm_mgau.c(838): Maximum top-N: 4
INFO: phone_loop_search.c(114): State beam -225 Phone exit beam -225 Insertion penalty 0
INFO: dict.c(320): Allocating 138824 * 32 bytes (4338 KiB) for word entries
INFO: dict.c(333): Reading main dictionary: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/cmudict-en-us.dict
INFO: dict.c(213): Dictionary size 134723, allocated 1016 KiB for strings, 1679 KiB for phones
INFO: dict.c(336): 134723 words read
INFO: dict.c(358): Reading filler dictionary: /home/exbot/workspace/git/sphinx/pocketsphinx/model/en-us/en-us/noisedict
INFO: dict.c(213): Dictionary size 134728, allocated 0 KiB for strings, 0 KiB for phones
INFO: dict.c(361): 5 words read
INFO: dict2pid.c(396): Building PID tables for dictionary
INFO: dict2pid.c(406): Allocating 42^3 * 2 bytes (144 KiB) for word-initial triphones
INFO: dict2pid.c(132): Allocated 42672 bytes (41 KiB) for word-final triphones
INFO: dict2pid.c(196): Allocated 42672 bytes (41 KiB) for single-phone word triphones
INFO: ngram_model_trie.c(354): Trying to read LM in trie binary format
INFO: ngram_search_fwdtree.c(74): Initializing search tree
INFO: ngram_search_fwdtree.c(101): 791 unique initial diphones
INFO: ngram_search_fwdtree.c(186): Creating search channels
INFO: ngram_search_fwdtree.c(323): Max nonroot chan increased to 152609
INFO: ngram_search_fwdtree.c(333): Created 723 root, 152481 non-root channels, 53 single-phone words
INFO: ngram_search_fwdflat.c(157): fwdflat: min_ef_width = 4, max_sf_win = 25
INFO: ngram_search.c(467): Resized score stack to 200000 entries
INFO: ngram_search.c(459): Resized backpointer table to 10000 entries
INFO: ngram_search.c(467): Resized score stack to 400000 entries
INFO: ngram_search.c(459): Resized backpointer table to 20000 entries
INFO: ngram_search_fwdtree.c(949): cand_sf[] increased to 64 entries
INFO: ngram_search.c(467): Resized score stack to 800000 entries
INFO: ngram_search.c(459): Resized backpointer table to 40000 entries
INFO: cmn_live.c(120): Update from <  0.00  -nan  -nan  0.00  0.00  -nan  -nan  -nan  -nan  -nan  -nan  -nan  0.00 >
INFO: cmn_live.c(138): Update to   < 41.00 -5.29 -0.12  5.09  2.48 -4.07 -1.37 -1.78 -5.08 -2.05 -6.45 -1.42  1.17 >
INFO: ngram_search_fwdtree.c(1550):    29532 words recognized (113/fr)
INFO: ngram_search_fwdtree.c(1552):  1163982 senones evaluated (4443/fr)
INFO: ngram_search_fwdtree.c(1556): 14031280 channels searched (53554/fr), 182655 1st, 1205164 last
INFO: ngram_search_fwdtree.c(1559):    52210 words for which last channels evaluated (199/fr)
INFO: ngram_search_fwdtree.c(1561):  3201243 candidate words for entering last phone (12218/fr)
INFO: ngram_search_fwdtree.c(1564): fwdtree 21.19 CPU 8.088 xRT
INFO: ngram_search_fwdtree.c(1567): fwdtree 21.20 wall 8.090 xRT
INFO: ngram_search_fwdflat.c(302): Utterance vocabulary contains 640 words
INFO: ngram_search_fwdflat.c(948):    15831 words recognized (60/fr)
INFO: ngram_search_fwdflat.c(950):   725720 senones evaluated (2770/fr)
INFO: ngram_search_fwdflat.c(952):  2428204 channels searched (9267/fr)
INFO: ngram_search_fwdflat.c(954):    94870 words searched (362/fr)
INFO: ngram_search_fwdflat.c(957):    65583 word transitions (250/fr)
INFO: ngram_search_fwdflat.c(960): fwdflat 2.42 CPU 0.922 xRT
INFO: ngram_search_fwdflat.c(963): fwdflat 2.42 wall 0.922 xRT
INFO: ngram_search.c(1250): lattice start node <s>.0 end node </s>.213
INFO: ngram_search.c(1276): Eliminated 0 nodes before end node
INFO: ngram_search.c(1381): Lattice has 2938 nodes, 77930 links
INFO: ps_lattice.c(1380): Bestpath score: -19740
INFO: ps_lattice.c(1384): Normalizer P(O) = alpha(</s>:213:260) = -1272819
INFO: ps_lattice.c(1441): Joint P(O,S) = -1435466 P(S|O) = -162647
INFO: ngram_search.c(872): bestpath 2.21 CPU 0.846 xRT
INFO: ngram_search.c(875): bestpath 2.21 wall 0.846 xRT
Recognized: if as it and and and and
INFO: ngram_search_fwdtree.c(429): TOTAL fwdtree 21.19 CPU 8.119 xRT
INFO: ngram_search_fwdtree.c(432): TOTAL fwdtree 21.20 wall 8.121 xRT
INFO: ngram_search_fwdflat.c(176): TOTAL fwdflat 2.42 CPU 0.926 xRT
INFO: ngram_search_fwdflat.c(179): TOTAL fwdflat 2.42 wall 0.926 xRT
INFO: ngram_search.c(303): TOTAL bestpath 2.21 CPU 0.846 xRT
INFO: ngram_search.c(306): TOTAL bestpath 2.21 wall 0.846 xRT

**Comment by nshmyrev** [comment]
Seems like some compiler incompatibility. Initial cmn line should not look like this:

` 0.00 -nan -nan 0.00 0.00 -nan -nan -nan -nan -nan -nan -nan 0.00
`

Provide details about compiler you have and the platform (os, version, hardware).

**Comment by tom8382** [comment]
hi nshmyrev,
  i am using:
  ubuntu 14.04
  gcc version 4.8.4
  x86_64-linux-gnu

  am i missing some configuraiton in makefile??

**Comment by nshmyrev** [comment]
Did you change the goforward.raw file?
