### ISSUE TITLE
Improving Accuracy and Rejecting Noise with mod_pocketsphinx on Freeswitch

### ISSUE THREAD

**Issue by santhosh-kumar** [cmusphinx/pocketsphinx#75]
We are using mod_pocketsphinx integration with Freeswitch to perform a simple "accept" call feature. Here is the grammar:
-----

#JSGF V1.0;
/**
  * JSGF Grammar for PTA
  */
grammar call_accept;

public <command> = <keyword>;

<keyword> = (accept);

-------
While testing a set of sample captures (.pcap) we found a very high false positive rate for the following cases:

gibberish.pcap with random words (https://www.dropbox.com/s/68b2ju7ha3i34mg/gibberish.pcap?dl=0)

background_music.pcap with a music played in the background (https://www.dropbox.com/s/h1yzd4arkcwybaw/background_music.pcap?dl=0)

**Note:** Decode the above pcap file as "RTP" on wireshark.

Also, we found that other words such as "okay" and "yes" are wrongly detected as "accept". We see that confidence is 100% in all those cases.

How do we improve this scenario? Should we define an extensive grammar?

We followed: https://sourceforge.net/p/cmusphinx/discussion/help/thread/1c6cb941/?limit=50#efa9 with no luck in mod_pocketsphinx for Freeswitch. 

Any thoughts/suggestion?

**Comment by nshmyrev** [comment]
Continuous listening requires keyword spotting mode as described in documentation.
