### ISSUE TITLE
resampling live audio from microphone

### ISSUE THREAD

**Issue by saibharani** [cmusphinx/pocketsphinx#78]
I want to recognize a keyword from live microphone recording, my sound card supports only 44100Hz sample rate but pocketsphinx works best at 16000hz sample rate. so i want to downsample recorded audio from 44100hz to 16000hz i am using pyaudio to record and my os is ubuntu 16.0.4 can anyone please suggest me a way to do it

**Comment by nshmyrev** [comment]
Use pulseaudio, it does downsampling.

**Comment by saibharani** [comment]
can you please explain me how to use pulseaudio to downsample i am new to programming

**Comment by ss-pq** [comment]
Sure, don’t!
Go forward!
