### ISSUE TITLE
pocketsphinx_continuous -samprate 8000 don't work

### ISSUE THREAD

**Issue by top1st** [cmusphinx/pocketsphinx#79]
-hmm ../../model/en-us/en-us
-lm ../../model/en-us/en-us.lm.bin
-dict ../../model/en-us/cmudict-en-us.dict
-samprate 8000
-upperf 3700

i have changed pocketsphinx.args like above
![screenshot_27](https://user-images.githubusercontent.com/23559697/27486629-cfa76fce-5863-11e7-833b-c01af541aa36.png)

Please help me this problem. I need too recognition 

i have to recognition this file but accuracy is very very low.

[rg-600-2672723344-20170207-120817-1486487286.998.wav.zip](https://github.com/cmusphinx/pocketsphinx/files/1098092/rg-600-2672723344-20170207-120817-1486487286.998.wav.zip)

current result after change file to 16000Hz 256kbps mono.

 
you
my
they like that but for bluebird cured the a quick aboveboard literally trying about fifteen minutes on deck and act upon all the optical to flirt and i could be done but one in the top of korea all that are not now but i got out of the bill you got on the number please and on alert the specks of them
the women on one one what would you come up with that need to build the track and now we have the word and the court that he should recover and
yeah obligatory
i knew they'd hold your chicken ewald tube
what that roller letter
i'd like to have better short doubled the question
how would that look out there working that pump of y'all we actually had to turn out cordoba identity awkwardly protector
i'm an adult and a big eyes and that you would bet that blubber cope with that we do love colby i'd love to enter
and cheddar and the
okano jerky tomato and bacon
and legislators bread and at that like that that that the are leading us on the arm so we're the job of it but i should really cared yet but yet but i'm not real court because uttered a word that
according to the data at illustrated
i mean it will tour so the yom pulled though the chicken it'll look crackers and a couple to what will avoid on that open to beam ninety
robert byrd got on the bet that
good
the novel has got to it that to the gamble problem ignorant cut
i thought proper to what they take their

**Comment by nshmyrev** [comment]
You need to download 8khz model from downloads

**Comment by top1st** [comment]
Thank you Mr. nshmyrev. It works well 👍
