### ISSUE TITLE
pocketsphinx timestamp error

### ISSUE THREAD

**Issue by russianjap** [cmusphinx/pocketsphinx#8]
I'm trying to get a timestamp of each word using ps_seg_frames. However, the timestamps are not lining up correctly to the words. I believe it has something to do with the silences not being timed accurately. When I compare the start and end times of each word, it is the correct length of time, however the silences are being recorded as much shorter than they actually are. 

Does anyone know a good way to fix this? Is there a way to record also how long a silence is? Or maybe should I restart the utterance after each word? If so how do you do this? 

I'm a beginner to sphinx and would appreciate any help. Thanks!

**Comment by nshmyrev** [comment]
Please provide the file you have trouble with.

**Comment by russianjap** [comment]
Do you mean the code? This is the function
![code](https://cloud.githubusercontent.com/assets/9053855/6587790/4e72fbcc-c75f-11e4-9a04-1f4b64750d22.png)

**Comment by nshmyrev** [comment]
The audio file

**Comment by russianjap** [comment]
This is a snippet of the audio. The full audio is 6 min long
https://www.dropbox.com/s/uw0lxu86gpq3e8n/test.wav?dl=0

**Comment by nshmyrev** [comment]
Ok, so in this audio which word timestamp is wrong?

**Comment by russianjap** [comment]
This is the output
<s> 0.000000 0.020000
ORIFICE 0.030000 0.600000
<sil> 0.610000 1.090000
YEAH 1.100000 1.260000
<sil> 1.270000 1.810000
RETROFLEXION 1.820000 2.510000
IN 2.520000 2.640000
THE(2) 2.650000 2.840000
ASCENDING 2.850000 3.270000
COLON 3.280000 3.790000
</s> 3.800000 4.160000

**Comment by russianjap** [comment]
This is the output 
(s) 0.000000 0.020000
ORIFICE 0.030000 0.600000
(sil) 0.610000 1.090000
YEAH 1.100000 1.260000
(sil) 1.270000 1.810000
RECTROFLEXION 1.820000 2.510000
IN 2.520000 2.640000
THE(2) 2.650000 2.840000
ASCENDING 2.850000 3.270000
COLON 3.280000 3.790000
(/s) 3.800000 4.160000"

**Comment by russianjap** [comment]
So because of the silences being condensed none of the timestamps are correct....

**Comment by nshmyrev** [comment]
Do you restart the search between utterances? You should start a new utterance once silence is detected as in pocketsphinx_continuous.c

`pocketsphinx_continuous -time yes -infile test.wav`

 prints correct timestampls

**Comment by russianjap** [comment]
Oh okay. How do you keep track of the time between utterances tho?

**Comment by nshmyrev** [comment]
Yes, you can use ps_start_stream to reset count.
