### ISSUE TITLE
Please help me improve 8000hz 128kbps wav file accuracy.

### ISSUE THREAD

**Issue by top1st** [cmusphinx/pocketsphinx#80]
-hmm ../../model/en-us/en-us-8000
-lm ../../model/en-us/en-us.lm.bin
-dict ../../model/en-us/cmudict-en-us.dict
-samprate 8000

i used this for 8000hz 128kbps file .
But really accuracy is not good as expected.
[rest.zip](https://github.com/cmusphinx/pocketsphinx/files/1100323/rest.zip)

Comparison.txt is paid result.   rg-600-.....wav.txt is sphinx result.

**Comment by nshmyrev** [comment]
Does not sound like an issue. When you pay for things they are usually better.
