### ISSUE TITLE
Please help me 8000Hz accuracy.

### ISSUE THREAD

**Issue by top1st** [cmusphinx/pocketsphinx#81]
i have found 128kbps/8000hz wav file in /pocketsphinx/test/data/wsj/n800_440c0201.wav

Please give me best option for this file recognition,
I used in pocketsphinx_continuous.

-hmm ../../model/en-us/en-us-8000
-lm ../../model/en-us/en-us.lm.bin
-dict ../../model/en-us/cmudict-en-us.dict
-samprate 8000

my result is "eight"

seems real data "at n. e. c. the need for international managers will keep rising"

please help me a bit to get some more high accuracy

**Comment by nshmyrev** [comment]
You are probably using older pocketsphinx. Current result is 'if he is the official managers will keep rising'
