### ISSUE TITLE
Namespace collision on Debian

### ISSUE THREAD

**Issue by mertyildiran** [cmusphinx/pocketsphinx#85]
While I was trying to pack a project for Debian that using `import pocketsphinx` Python module, I realized that there is a **namespace collision** between: 
https://pypi.python.org/pypi/pocketsphinx (source: https://github.com/bambocher/pocketsphinx-python)
and 
https://packages.debian.org/jessie/python/python-pocketsphinx (source: https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python)

Also it's **uncertain** that which one of these projects are the official Python bindings for pocketsphinx:

- https://github.com/cmusphinx/pocketsphinx/tree/master/swig/python

- https://github.com/bambocher/pocketsphinx-python

- https://github.com/cmusphinx/pocketsphinx-python

Please make it clarify and fix this namespace collision.

**Comment by nshmyrev** [comment]
Same asked at https://github.com/cmusphinx/pocketsphinx-python/issues/34
