### ISSUE TITLE
swig c# Makefile gcc arguments

### ISSUE THREAD

**Issue by fgeraci** [cmusphinx/pocketsphinx#87]
Hello

I wasn't able to compile (gcc third rule) until I reversed the .c files and libraries linking order.

    libpocketsphinxwrap.so: pocketsphinx.c
        gcc -fPIC pocketsphinx.c sphinxbase.c `pkg-config --libs --cflags pocketsphinx` -shared -o $@

Before that libraries were undefined for the linker.

**Comment by dhdaines** [comment]
No longer relevant as the build system has changed (#250)
