### ISSUE TITLE
wrong recognition

### ISSUE THREAD

**Issue by VBR1016** [cmusphinx/pocketsphinx#89]
Hi Everybody!
I've installed pocketsphinx in Windows 10 and I've written exactly the programs in it's examples.
and i've used it's model and dictionary.
but it does'nt work at all , it means it can't recognize a word correctly at all.
I don't know what should I do.
please help me.
Thank you so much.

**Comment by nshmyrev** [comment]
Ask for help on forum and provide the audio file you are trying to recognize.
