### ISSUE TITLE
Why /pocketsphinx/blob/master/model/en-us/cmudict-en-us.dict is different from /cmudict/blob/master/cmudict.dict?

### ISSUE THREAD

**Issue by Coeur** [cmusphinx/pocketsphinx#97]
Why https://github.com/cmusphinx/pocketsphinx/blob/master/model/en-us/cmudict-en-us.dict is different from https://github.com/cmusphinx/cmudict/blob/master/cmudict.dict? Different size, different history.

Is there a justification for the difference? Could we realign to only keep the _best_ one if any?

Or at least document the difference and link to the other one on each repository to allow users to notice the alternative and allow them to make a choice.

**Comment by nshmyrev** [comment]
> Is there a justification for the difference? 

cmudict repo is primary source. pocketsphinx version is included to simplify setup

> Or at least document the difference and link to the other one on each repository to allow users to notice the alternative and allow them to make a choice.

Feel free to submit a pull request.
