### ISSUE TITLE
Using PocketSphinnx to Search for words within an audio file

### ISSUE THREAD

**Issue by deolu007** [cmusphinx/pocketsphinx#98]
I am trying to use pocketsphinx to search for a word within an audio file.

my command: pocketsphinx_continuous -infile success.wav -hmm en-us -kws_threshold 1e-40 -keyphrase "success" -time yes

error: INFO: feat.c(715): Initializing feature stream to type: '1s_c_d_dd', ceplen=13, CMN='live', VARNORM='no', AGC='none'
ERROR: "acmod.c", line 79: Folder 'en-us' does not contain acoustic model definition 'mdef'

**Comment by nshmyrev** [comment]
You need to properly specify the path to the acoustic model with -hmm argument.
